---
title: "2HT Modeling"
author: "William Hopper"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---
```{css css, echo=FALSE, cache=FALSE}
.main-container {
    max-width: 1200px;
  }
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", cache=TRUE)
library(rprojroot)
library(ggplot2)
library(kableExtra)
library(optimx)
library(foreach)
library(rstan)
library(tidybayes)
library(MPTinR)
library(doParallel)
library(ggplot2)
library(tidyr)
library(dplyr)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
root_dir <- rprojroot::is_rstudio_project$find_file()
```

```{r load_data}
load(file.path(root_dir, "data","SvDPRec.Rdata"))
test <- select(test, -list)
```

# By-Subject Modeling

```{r cell_counts, dependson="load_data"}
delayed_counts_by_sub_bias <- filter(test, !is.na(type)) %>%
  select(-starts_with("speeded")) %>%
  rename(correct = delayed_correct) %>%
  count(subject, strength, pOld, correct) %>%
  complete(subject, strength, pOld, correct,
           fill = list(n=0)) %>%
  unite(col = "resp_type", strength, correct) %>%
  spread(resp_type, n) %>%
  rename(FA = L_FALSE, CR = L_TRUE,
         M_S = S_FALSE, H_S = S_TRUE,
         M_W = W_FALSE, H_W = W_TRUE) %>%
  mutate(L_N = FA + CR,
         S_N = M_S + H_S,
         W_N = M_W + H_W) %>%
  select(subject, pOld, FA, L_N, H_S, S_N, H_W, W_N)

```

```{r empirical_roc_data, dependson="cell_counts"}
obs_ROC_data <- mutate(delayed_counts_by_sub_bias,
                       FAR = FA/L_N,
                       HR_W = H_W/W_N,
                       HR_S = H_S/S_N,
                       pOld = sprintf("%2.0f%%", pOld*100)) %>%
  select(subject, pOld, FAR, HR_W, HR_S) %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  select(subject, pOld, strength, FAR, HR)

avg_obs_ROC_data <- group_by(obs_ROC_data, pOld, strength) %>%
  summarise_at(.vars = c("FAR", "HR"), .funs = "mean") %>%
  ungroup()
```

```{r null_LL, dependson=c("cell_counts")}
null_LL <- mutate(delayed_counts_by_sub_bias,
                  FA_LL = dbinom(FA, L_N, FA / L_N, log = TRUE),
                  HW_LL = dbinom(H_W, W_N, H_W / W_N, log = TRUE),
                  HS_LL = dbinom(H_S, S_N, H_S / S_N, log = TRUE),
                  LL = FA_LL + HW_LL + HS_LL) %>% 
  select(subject, pOld, LL) %>%
  group_by(subject) %>%
  summarise(null_LL = sum(LL))
```

## Hierarchical Bayesian Estimation

```{stan stan_model_external, cache=FALSE, eval=FALSE, echo=TRUE, output.var='modelstring', code=readLines(file.path(root_dir, "R","2HT.stan"))}
```

```{r stan_model, results="hide", dependson="cell_counts", cache.extra = tools::md5sum(file.path(root_dir, "R","2HT.stan"))}
# Create an array suitable for passing into stan, so it can be turned into an array of matrices
# The final produce should be 14 x 3 x 3, with subject along dim 1, bias level (conservative --> liberal) along dim 2,
# and strength (lure, weak, strong) along dim 3.
corrects_matrix <- arrange(delayed_counts_by_sub_bias, subject, desc(pOld)) %>%
  mutate(CR = L_N - FA,
         H_S = replace(H_S, H_S == S_N, H_S[H_S == S_N]-1)) %>%
  as.matrix(x=.[,c('CR','H_W','H_S')], rownames.force = FALSE) %>%
  t()
dim(corrects_matrix) <- c(3, 3, 14)
dimnames(corrects_matrix) <- list("Strength" = c("Lure","Weak","Strong"),
                                  "Bias" = c("Lib.", "Neutral", "Cons."),
                                  "Subject" = 101:114)
corrects_matrix <- aperm(corrects_matrix, c(2,1,3))

trial_matrix <- arrange(delayed_counts_by_sub_bias, subject, desc(pOld)) %>%
  mutate(CR = L_N - FA,
         H_S = replace(H_S, H_S == S_N, H_S[H_S == S_N]-1)) %>%
  as.matrix(x=.[,c('L_N','W_N','S_N')], rownames.force = FALSE) %>%
  t()
dim(trial_matrix) <- c(3, 3, 14)
dimnames(trial_matrix) <- list("Strength" = c("Lure","Weak","Strong"),
                               "Bias" = c("Lib.","Neutral","Cons."),
                               "Subject" = 101:114)
trial_matrix <- aperm(trial_matrix, c(2,1,3))

standata <- list(corrects = corrects_matrix, trials = trial_matrix,
                 Nsubs = length(unique(delayed_counts_by_sub_bias$subject)))

twoHT_stan_fit <- stan(file = file.path(root_dir, "R","2HT.stan"),
                       data = standata,
                       iter = 3000,
                       chains = 4,
                       seed = 1235,
                       init_r = 1,
                       control = list(adapt_delta = .99, max_treedepth = 15)
                       )
twoHT_stan_fit <- recover_types(twoHT_stan_fit)
rm(corrects_matrix, trial_matrix, standata)
```

```{r stan_parameter_summaries, dependson="stan_model"}
twoHT_stan_subject_params <- spread_draws(twoHT_stan_fit, `GO_.*`[subject], `D.*`[subject], regex=TRUE) %>%
  ungroup() %>%
  mutate(subject = as.character(subject + 100)) %>%
  group_by(subject)

twoHT_stan_subject_param_summaries <- mean_hdi(twoHT_stan_subject_params)
  
twoHT_stan_pop_params <- spread_draws(twoHT_stan_fit, `beta_.*`[parameter_index], regex=TRUE)

param_index_key <- c("DN", "DO_W", "DO_S", "GO_Lib", "GO_Neut", "GO_Cons")

twoHT_stan_pop_param_summaries <- mean_hdi(twoHT_stan_pop_params) %>%
  select(-.point, -.interval, -.width) %>%
  mutate(parameter_index = param_index_key[parameter_index]) %>%
  gather("param", "value", -parameter_index) %>%
  mutate(param = sub("beta_", "", param)) %>%
  unite(col=param, parameter_index, param) %>%
  spread(param, value)

rm(param_index_key)
```

```{r stan_ROC_predictions, dependson="stan_model"}

FAR_points <- seq(0, 1, .01)

twoHT_stan_ROC_curve <- group_by(twoHT_stan_subject_param_summaries, subject) %>%
  summarise(twoHT = list(
    data.frame(FAR = rep(FAR_points, 2),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels = c("W", "S")),
               HR = c( ((1-DO_W)/(1-DN)*FAR_points) + DO_W,
                       ((1-DO_S)/(1-DN)*FAR_points) + DO_S
               ))
    
    )) %>%
  select(subject, twoHT) %>%
  unnest() %>%
  filter(HR <= 1)

detect_params <- select(twoHT_stan_subject_param_summaries, subject, DN, DO_W, DO_S) %>%
  gather("strength","detect_prob", -subject) %>%
  mutate(strength = recode(strength, DN = "L", DO_W = "W", DO_S = "S"))

bias_params <- select(twoHT_stan_subject_param_summaries, subject, GO_Lib, GO_Neut, GO_Cons) %>%
  gather("pOld","guess_old_prob", -subject) %>%
  mutate(pOld = recode(pOld, GO_Lib = "75%", GO_Neut = "50%", GO_Cons = "25%"))

twoHT_stan_ROC_points <- full_join(detect_params, bias_params, by="subject") %>%
  select(subject, strength, pOld, detect_prob, guess_old_prob) %>%
  arrange(subject,strength, pOld) %>%
  mutate(guess_correct_prob = ifelse(strength=="L", 1-guess_old_prob, guess_old_prob),
         pCorrect = detect_prob + (1-detect_prob)*(guess_correct_prob)) %>%
  select(subject, strength, pOld, pCorrect) %>%
  spread(strength, pCorrect) %>%
  mutate(FAR = 1-L) %>%
  select(subject, pOld, FAR, HR_W = W, HR_S = S) %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  select(subject, pOld, strength, FAR, HR) %>%
  bind_rows(pred = ., obs = obs_ROC_data, .id = "type") %>%
  arrange(subject, pOld, strength, type)

rm(detect_params, bias_params)
```


```{r column_names_map}
formatted_names_map <- c(subject="Subject", model="model", DN="DN<sub>L</sub>", DO_W="DO<sub>W</sub>", 
                         DO_S="DO<sub>S</sub>", GO_Cons="GO<sub>C</sub>", GO_Neut="GO<sub>N</sub>",
                         GO_Lib="GO<sub>L</sub>", G2="G<sup>2</sup>", LL="LL",
                         null_LL="Null LL", df="df", p="p(X<sup>2</sup>)",fevals="fevals",
                         gevals="gevals", niter="niter", convcode="convcode", mean="Mean",
                         HDI="HDI", p.value = "<i>p</i>"
                         )
```


```{r stan_ROC_plot, results="asis", dependson="stan_model", fig.height=12, fig.width=12}

ROC <- ggplot(twoHT_stan_ROC_points,
              aes(x=FAR, y=HR, color=type, shape=pOld)
              ) +
  geom_line(aes(x=FAR, y=HR, color=type, linetype=strength),
            data = mutate(twoHT_stan_ROC_curve, type="pred"),
            size=1,
            inherit.aes = FALSE
            ) +  
  geom_line(aes(linetype=strength, group=strength),
            data = filter(twoHT_stan_ROC_points, type=="obs"),
            size=1) +
  geom_point(size=2) +
  facet_wrap(~subject, ncol=4, labeller = label_both) +
  scale_x_continuous("False Alarm Rate",
                     limits = c(0,1),
                     breaks = c(0,0.25, 0.5, 0.75, 1),
                     labels = c("0",".25", ".5", ".75", "1")
                     ) +
  scale_y_continuous("Hit Rate",
                     limits = c(0,1),
                     breaks = c(0,0.25, 0.5, 0.75, 1),
                     labels = c("0",".25", ".5", ".75", "1")
                     ) +
  scale_colour_brewer("Model",
                      palette = "Set1",
                      limits = c("obs", "pred"),
                      labels = c("obs" = "Observed",
                                 "pred" = "Bayesian\nTwo HT")
                      ) +
  scale_linetype_discrete("Strength",
                          limits = c("W", "S"),
                          labels = c("W" = "Weak", "S" = "Strong")
                          ) +
  coord_equal() +
  ggtitle("Predicted ROC for delayed judgments") +
  theme_bw(base_size = 16) +
  theme(legend.position = c(.75, .1),
        legend.box = "horizontal",
        legend.key.height = unit(1.5, "lines")
        )
print(ROC)


param_table <- 
  select(twoHT_stan_subject_param_summaries,
         -.width, -.interval, -.point) %>%
  gather("param", "value", -subject) %>%
  separate(param, into = c("param","stat"), sep = "\\.",
           fill="right") %>%
  spread(stat, value) %>%
  select(subject, param, mean = `<NA>`, lower, upper) %>% 
  mutate(lower = round(lower, 3),
         upper = round(upper, 3),
         HDI = paste("[", lower, ", ", upper, "]", sep="")
         ) %>%
  select(subject, param, mean, HDI) %>%
  nest(mean, HDI, .key = "x") %>%
  spread(key="param", value = x)

top_level_labels <- formatted_names_map[names(param_table)[-1]]

param_table <- unnest(param_table)

knitr::kable(param_table,
             digits=3, type="html", escape=FALSE,
             col.names = sub("[[:digit:]]+$", "", tools::toTitleCase(names(param_table)))
             ) %>%
  kable_styling(full_width = FALSE) %>%
  add_header_above(setNames(c(1, rep(2, length(top_level_labels))),
                            c(" ", top_level_labels)
                            ),
                   escape = FALSE
                   ) %>%
  row_spec(0, align = "c") %>%
  column_spec(1, bold=TRUE) %>%
  print()

```

```{r save_outputs, cache=FALSE, eval=isTRUE(getOption('knitr.in.progress'))}
files_dir <- paste0(tools::file_path_sans_ext(knitr::current_input()),
                    "_files"
                    )
if (!dir.exists(files_dir)) {
  dir.create(files_dir)
}

write.csv(twoHT_stan_subject_param_summaries,
          file = file.path(files_dir, "subject_parameters.csv"),
          row.names = FALSE
          )
write.csv(twoHT_stan_pop_param_summaries,
          file = file.path(files_dir, "pop_parameters.csv"),
          row.names = FALSE
          )
save(twoHT_stan_fit, file=file.path(files_dir, "twoHT_stan_posterior.Rdata"))
```


```{r download_links, cache=FALSE, results="asis"}
cat("<ul><li>",
    paste0('<a href="', file.path(files_dir, "subject_parameters.csv"),
           '">Download Subject Parameters</a>'
           ),
    "</li><li>",
    paste0('<a href="',
           file.path(files_dir, "pop_parameters.csv"),
           '">Download Population Parameters</a>'
       ),
    "</li><li>",
    paste0('<a href="',
           file.path(files_dir, "twoHT_stan_posterior.Rdata"),
           '">Download Posterior Samples</a>'
       ),
    "</li></ul>",
    sep=""
    )
```


## MLE Version

### Standard MLE
```{r std_2HT_LL}
twoHT <- function(theta) {
  
  FAR <- (1-theta['DN'])*theta[c("GO_Cons", "GO_Neut", "GO_Lib")]
  HR_W <- theta['DO_W'] + ((1-theta['DO_W'])*theta[c("GO_Cons", "GO_Neut", "GO_Lib")])
  HR_S <- theta['DO_S'] + ((1-theta['DO_S'])*theta[c("GO_Cons", "GO_Neut", "GO_Lib")])

  return(list(FAR=FAR, HR_W=HR_W, HR_S=HR_S))
}

twoHT_LL <- function(theta, counts) {
  
  preds <- twoHT(theta)

  LL <- c(dbinom(counts$H_S, size = counts$S_N, prob = preds$HR_S, log=TRUE),
          dbinom(counts$H_W, size = counts$W_N, prob = preds$HR_W, log=TRUE),
          dbinom(counts$FA, size = counts$L_N, prob = preds$FAR, log=TRUE)
          )
  return(-sum(LL))
}

twoHT_G2 <- function(theta, counts) {
  
  preds <- twoHT(theta)

  LL <- c(dbinom(counts$H_S, size = counts$S_N, prob = preds$HR_S, log=TRUE),
          dbinom(counts$H_W, size = counts$W_N, prob = preds$HR_W, log=TRUE),
          dbinom(counts$FA, size = counts$L_N, prob = preds$FAR, log=TRUE)
          )
  return(-sum(LL))
}
```

```{r std_2HT_fit, dependson=c("std_2HT_LL","cell_counts")}
twoHT_std_fit_optimx <- foreach(sub = split(delayed_counts_by_sub_bias,
                                           delayed_counts_by_sub_bias$subject)
                            ) %do% {

    fit <- optimx(par = c("DN"=.5, "DO_W"=.5, "DO_S"=.75,
                          "GO_Cons"=.25, 'GO_Neut'=.5, 'GO_Lib'=.75
                          ),
                  fn = twoHT_LL,
                  method = "nlminb",
                  itnmax = 3000,
                  lower = c(0, 0, 0, 0, 0, 0),
                  upper = c(1, 1, 1, 1, 1, 1),
                  control = list(kkt=FALSE),
                  counts = sub
                  )
    fit$subject <- sub$subject[1]
    fit
  }
rm(fit, sub)
```

```{r std_twoHT_GOF, dependson="std_2HT_fit"}
twoHT_std_fits <- bind_rows(twoHT_std_fit_optimx)

twoHT_std_params <- select(twoHT_std_fits, subject, !!!c("DN", "DO_W", "DO_S", "GO_Cons", "GO_Neut", "GO_Lib"))
twoHT_std_avg_params <- summarise_at(twoHT_std_params,
                                     .vars = c("DN", "DO_W", "DO_S", "GO_Cons", "GO_Neut", "GO_Lib"),
                                     .funs = "mean")

twoHT_std_GOF <- select(twoHT_std_fits, subject, LL = value, fevals, gevals, niter, convcode) %>%
  mutate(LL = -LL) %>%
  left_join(null_LL, by="subject") %>%
  mutate(calc_G2 = -2*(LL - null_LL)) %>%
  mutate(df = 3,
         p.value = pchisq(calc_G2, df=df, lower.tail = FALSE)
         ) %>%
  select(subject, LL, null_LL, calc_G2, df, p.value, fevals:convcode)

twoHT_std_sum_GOF <- select(.data = twoHT_std_GOF,
                            subject, LL, null_LL, calc_G2, df) %>%
  summarise_at(.vars = c("LL", "null_LL", "calc_G2", "df"),
               .funs = "sum"
               ) %>%
  mutate(p.value = pchisq(calc_G2, df=df, lower.tail = FALSE))

rm(twoHT_std_fits)
```

```{r std_twoHT_ROC_predictions, dependson="std_2HT_fit"}

twoHT_std_sub_ROC_curve <- group_by(twoHT_std_params, subject) %>%
  mutate(twoHT = list(
    data.frame(FAR = rep(FAR_points, 2),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels = c("W", "S")),
               HR = c( ((1-DO_W)/(1-DN)*FAR_points) + DO_W,
                       ((1-DO_S)/(1-DN)*FAR_points) + DO_S
               ))
    
    )) %>%
  select(subject, twoHT) %>%
  unnest() %>%
  filter(HR <= 1)

twoHT_std_avg_ROC_curve <- select(twoHT_std_params, -subject) %>%
  summarise_all("mean") %>%
  summarise(twoHT = list(
    data.frame(FAR = rep(FAR_points, 2),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels = c("W", "S")),
               HR = c( ((1-DO_W)/(1-DN)*FAR_points) + DO_W,
                       ((1-DO_S)/(1-DN)*FAR_points) + DO_S
               ))
    
    )) %>%
  unnest() %>%
  filter(HR <= 1)


twoHT_std_sub_ROC_points <- group_by(twoHT_std_params, subject) %>%
  mutate(x = list(data.frame(
           twoHT(c("DN"=DN, "DO_W"=DO_W, "DO_S"=DO_S,
                   "GO_Cons"=GO_Cons, "GO_Neut"=GO_Neut, "GO_Lib"=GO_Lib
                 )),
           pOld = c("25%", "50%", "75%"),
           stringsAsFactors = FALSE
         ))) %>%
  select(subject, x) %>%
  unnest() %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  filter(HR <= 1) %>%
  select(subject, pOld, strength, FAR, HR) %>%
  bind_rows(pred = ., obs = obs_ROC_data, .id = "type")


twoHT_std_avg_ROC_points <- select(twoHT_std_params, -subject) %>%
  summarise_all("mean") %>%
  mutate(x = list(data.frame(
           twoHT(c("DN"=DN, "DO_W"=DO_W, "DO_S"=DO_S,
                   "GO_Cons"=GO_Cons, "GO_Neut"=GO_Neut, "GO_Lib"=GO_Lib
                 )),
           pOld = c("25%", "50%", "75%"),
           stringsAsFactors = FALSE
         ))) %>%
  select(x) %>%
  unnest() %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  filter(HR <= 1) %>%
  select(pOld, strength, FAR, HR) %>%
  bind_rows(pred = ., obs = avg_obs_ROC_data, .id = "type")
```


```{r std_twoHT_ROC_avg_plot, fig.width=6.5, fig.height=6.5, dependson="std_2HT_fit"}
ggplot(twoHT_std_avg_ROC_points,
       aes(x=FAR, y=HR, color=type, shape=pOld)
       ) +
  geom_line(aes(x=FAR, y=HR, color=type, linetype=strength),
            data = mutate(twoHT_std_avg_ROC_curve, type="pred"),
            size=1.75,
            inherit.aes = FALSE
            ) +
  geom_line(aes(linetype=strength, group=strength),
            data = filter(twoHT_std_avg_ROC_points, type=="obs"),
            size=1.75
            ) +
  geom_point(size=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)
                     ) +
  scale_y_continuous("Hit Rate", limits = c(0,1)
                     ) +
  scale_colour_brewer("Model",
                      palette = "Set1",
                      limits = c("obs", "pred"),
                      labels = c("obs" = "Observed",
                                 "pred" = "Two HT")
                      ) +
  scale_linetype_discrete("Strength",
                          limits = c("W", "S"),
                          labels = c("W" = "Weak", "S" = "Strong")
                          ) +
  coord_fixed() +
  ggtitle("Two-HT Model ROC (Average)") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.size = unit(2, "lines"),
        legend.position = c(.6, .2),
        legend.box = "horizontal"
        )
```


```{r std_twoHT_ROC_sub_plot, fig.width=12, fig.height=12, dependson="std_2HT_fit"}

ggplot(twoHT_std_sub_ROC_points,
       aes(x=FAR, y=HR, color=type, shape=pOld)
       ) +
  geom_line(aes(x=FAR, y=HR, color=type, linetype=strength),
            data = mutate(twoHT_std_sub_ROC_curve, type="pred"),
            size=1,
            inherit.aes = FALSE
            ) +
  geom_line(aes(linetype=strength, group=strength),
            data = filter(twoHT_std_sub_ROC_points, type=="obs"),
            size=1) +
  geom_point(size=2) +
  facet_wrap(~subject, ncol=4, labeller = label_both) +
  scale_x_continuous("False Alarm Rate",
                     limits = c(0,1),
                     breaks = c(0,0.25, 0.5, 0.75, 1),
                     labels = c("0",".25", ".5", ".75", "1")
                     ) +
  scale_y_continuous("Hit Rate",
                     limits = c(0,1),
                     breaks = c(0,0.25, 0.5, 0.75, 1),
                     labels = c("0",".25", ".5", ".75", "1")
                     ) +
  scale_colour_brewer("Model",
                      palette = "Set1",
                      limits = c("obs", "pred"),
                      labels = c("obs" = "Observed",
                                 "pred" = "Two HT")
                      ) +
  scale_linetype_discrete("Strength",
                          limits = c("W", "S"),
                          labels = c("W" = "Weak", "S" = "Strong")
                          ) +
  coord_equal() +
  ggtitle("Predicted ROC for delayed judgments") +
  theme_bw(base_size = 16) +
  theme(legend.position = c(.75, .1),
        legend.box = "horizontal",
        legend.key.height = unit(1.5, "lines")
        )
```


```{r std_twoHT_param_table, dependson="std_2HT_fit"}
x <- bind_rows(twoHT_std_params,
               mutate(twoHT_std_avg_params, subject = "Mean/Sum")
               )

y <- bind_rows(select(.data = twoHT_std_GOF, subject, G2=calc_G2),
               mutate(select(.data = twoHT_std_sum_GOF, G2=calc_G2),
                      subject = "Mean/Sum"
                      )
               )

left_join(x, y, by = "subject") %>%
  kable(type="HTML",
        digits=3,
        col.names = formatted_names_map[names(.)],
        escape=FALSE
        ) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  column_spec(1, bold = TRUE)

rm(x,y)
```



```{r save_MLE_outputs, cache=FALSE, eval=isTRUE(getOption('knitr.in.progress'))}
files_dir <- paste0(tools::file_path_sans_ext(knitr::current_input()),
                    "_files"
                    )
if (!dir.exists(files_dir)) {
  dir.create(files_dir)
}

write.csv(twoHT_std_params,
          file = file.path(files_dir, "parameters.csv"),
          row.names = FALSE
          )
write.csv(twoHT_std_GOF,
          file = file.path(files_dir, "GOF.csv"),
          row.names = FALSE
          )
```


```{r MLE_download_links, cache=FALSE, results="asis"}
cat("<ul><li>",
    paste0('<a href="', file.path(files_dir, "parameters.csv"),
           '">Download Parameters</a>'
           ),
    "</li><li>",
    paste0('<a href="',
           file.path(files_dir, "GOF.csv"),
           '">Download GOF Statistics</a>'
       ),
    "</li></ul>",
    sep=""
    )
```


### MPT 

```{r 2HT_model_and_data, dependson=c("cell_counts")}
twoHT_mpt_model <- "
# Tree for strong items in pOld=25% condition. First 'old', then 'new'
dS + (1-dS) * gC
(1-dS)*(1-gC)

# Tree for weak items in pOld=25% condition. First 'old', then 'new'
dW + (1-dW) * gC
(1-dW)*(1-gC)

#Tree for lures in pOld=25% condition. First 'old', then 'new'
(1-dN) * gC
dN + (1-dN) * (1 - gC)

# Tree for strong items in pOld=50% condition. First 'old', then 'new'
dS + (1-dS) * gN
(1-dS)*(1-gN)

# Tree for weak items in pOld=50% condition. First 'old', then 'new'
dW + (1-dW) * gN
(1-dW)*(1-gN)

#Tree for lures in pOld=50% condition. First 'old', then 'new'
(1-dN) * gN
dN + (1-dN) * (1 - gN)

# Tree for strong items in pOld=75% condition. First 'old', then 'new'
dS + (1-dS) * gL
(1-dS)*(1-gL)

# Tree for weak items in pOld=75% condition. First 'old', then 'new'
dW + (1-dW) * gL
(1-dW)*(1-gL)

#Tree for lures in pOld=75% condition. First 'old', then 'new'
(1-dN) * gL
dN + (1-dN) * (1 - gL)
"

twoHT_mpt_data_layout <- transmute(delayed_counts_by_sub_bias,
  subject,
  pOld,
  strong_old = H_S,
  strong_new = S_N - H_S,
  weak_old = H_W,
  weak_new = W_N - H_W,
  lure_old = FA,
  lure_new = L_N - FA) %>%
  gather("response","count", -subject, -pOld) %>%
  unite(condition, pOld, response) %>%
  spread(condition, count) %>%
  select(subject,
         `0.25_strong_old`, `0.25_strong_new`,
         `0.25_weak_old`, `0.25_weak_new`,
         `0.25_lure_old`, `0.25_lure_new`,
         `0.5_strong_old`, `0.5_strong_new`,
         `0.5_weak_old`, `0.5_weak_new`,
         `0.5_lure_old`, `0.5_lure_new`,
         `0.75_strong_old`, `0.75_strong_new`,
         `0.75_weak_old`, `0.75_weak_new`,
         `0.75_lure_old`, `0.75_lure_new`) %>%
  as.data.frame() %>%
  tibble::column_to_rownames("subject") %>%
  data.matrix()
```


```{r 2HT_fit, dependson="2HT_model_and_data"}
twoHT_mpt_fit <- fit.mpt(data = twoHT_mpt_data_layout,
                         model.filename = textConnection(twoHT_mpt_model),
                         show.messages = FALSE)
rm(twoHT_mpt_data_layout, twoHT_mpt_model)
```


```{r 2HT_mpt_param_table, dependson="2HT_fit"}
twoHT_mpt_params <- cbind(twoHT_mpt_fit$parameters$individual[,1,],
                          twoHT_mpt_fit$parameters$mean[,1, drop=FALSE]
                          ) %>%
  `colnames<-`(c(101:114, "Mean/Sum")) %>%
  t() %>%
  as.data.frame() %>%
  tibble::rownames_to_column("subject") %>%
  select(subject, DN = dN, DO_W=dW, DO_S=dS, GO_Cons=gC, GO_Neut=gN, GO_Lib=gL)


twoHT_mpt_GOF <- bind_rows(twoHT_mpt_fit$goodness.of.fit$individual,
                           twoHT_mpt_fit$goodness.of.fit$sum) %>%
  mutate(subject = c(101:114, "Mean/Sum"))

left_join(twoHT_mpt_params,
          select(twoHT_mpt_GOF, subject, G2=G.Squared),
          by = "subject"
          ) %>%
  kable(type="HTML",
        digits=3,
        col.names = formatted_names_map[names(.)],
        escape=FALSE
        ) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  column_spec(1, bold = TRUE)
```


### Std vs. MPT Parameter Comparison

```{r mpt_vs_std_scatterplot}
x <- gather(twoHT_std_params, "param", "std", -subject) %>%
  bind_rows(.,
            mutate(select(twoHT_std_GOF, subject, std=calc_G2),
                   param="G2")
            )

y <- gather(twoHT_mpt_params, "param", "mpt", -subject) %>%
  bind_rows(.,
            mutate(select(twoHT_mpt_GOF, subject, mpt=G.Squared),
                   param="G2")
            ) %>%
  filter(subject != "Mean/Sum")

ggplot(full_join(x, y, by = c("subject", "param")),
       aes(x=std, y=mpt)
       ) +
  geom_point() +
  geom_abline(intercept = 0, slope=1) +
  facet_wrap(~param, scales = "free") +
  ggtitle("MPT vs. Std. Parameters")

rm(x, y)
```

# Aggregated Modeling

```{r cell_counts_pooled}
delayed_counts_by_bias <-
  select(.data = delayed_counts_by_sub_bias, -subject) %>%
  group_by(pOld) %>%
  summarise_all(.funs = "sum")

obs_ROC_data_pooled <-
  mutate(delayed_counts_by_bias,
         FAR = FA / L_N,
         HR_W = H_W / W_N,
         HR_S = H_S / S_N,
         pOld = sprintf("%2.0f%%", pOld * 100)) %>%
  select(pOld, FAR, HR_W, HR_S) %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  select(pOld, strength, FAR, HR)
```


```{r null_LL_pooled}
null_LL_pooled <-
  mutate(delayed_counts_by_bias,
         FA_LL = dbinom(FA, L_N, FA / L_N, log = TRUE),
         HW_LL = dbinom(H_W, W_N, H_W / W_N, log = TRUE),
         HS_LL = dbinom(H_S, S_N, H_S / S_N, log = TRUE),
         LL = FA_LL + HW_LL + HS_LL) %>%
  select(pOld, LL) %>%
  summarise(null_LL = sum(LL))
```


```{r fit_std_2HT_pooled, dependson=c("cell_counts_pooled", "std_2HT_LL")}
twoHT_std_fit_pooled <- optimx(par = c("DN"=.5, "DO_W"=.5, "DO_S"=.75,
                                     "GO_Cons" = .25, 'GO_Neut' = .5, 'GO_Lib' = .75
                                     ),
                             fn = twoHT_LL,
                             method = "nlminb",
                             itnmax = 3000,
                             lower = c(0, 0, 0, 0, 0, 0),
                             upper = c(1, 1, 1, 1, 1, 1),
                             control = list(kkt = FALSE),
                             counts = delayed_counts_by_bias
                             )
```


```{r std_twoHT_pooled_GOF, dependson="fit_std_2HT_pooled"}

twoHT_std_GOF_pooled <-
  select(twoHT_std_fit_pooled, LL = value, fevals, gevals, niter, convcode) %>%
  mutate(LL = -LL) %>%
  bind_cols(null_LL_pooled) %>%
  mutate(G2 = -2*(LL - null_LL)) %>%
  mutate(df = 3,
         p.value = pchisq(G2, df=df, lower.tail = FALSE)
         ) %>%
  select(LL, null_LL, G2, df, p.value, fevals:convcode)
```


```{r std_twoHT_pooled_params, dependson="fit_std_2HT_pooled"}

twoHT_std_params_pooled <- select(.data = twoHT_std_fit_pooled,
                                  DN, DO_W, DO_S, GO_Cons, GO_Neut, GO_Lib
                                  )
rm(twoHT_std_fit_pooled)
```


```{r std_twoHT_ROC_pooled_predictions, dependson="std_twoHT_pooled_params"}

twoHT_std_ROC_curve_pooled <-
  mutate(.data = twoHT_std_params_pooled,
         twoHT = list(
    data.frame(FAR = rep(FAR_points, 2),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels = c("W", "S")),
               HR = c( ((1-DO_W)/(1-DN)*FAR_points) + DO_W,
                       ((1-DO_S)/(1-DN)*FAR_points) + DO_S
               ))
    
    )) %>%
  select(twoHT) %>%
  unnest() %>%
  filter(HR <= 1)

twoHT_std_ROC_points_pooled <-
  mutate(.data = twoHT_std_params_pooled,
         x = list(data.frame(
           twoHT(c("DN"=DN, "DO_W"=DO_W, "DO_S"=DO_S,
                   "GO_Cons"=GO_Cons, "GO_Neut"=GO_Neut, "GO_Lib"=GO_Lib
                 )),
           pOld = c("25%", "50%", "75%"),
           stringsAsFactors = FALSE
         ))) %>%
  select(x)%>%
  unnest() %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  filter(HR <= 1) %>%
  select(pOld, strength, FAR, HR) %>%
  bind_rows(pred = .,
            obs = obs_ROC_data_pooled,
            .id = "type")
```


```{r std_twoHT_ROC_pooled_plot, fig.width=6.5, fig.height=6.5, dependson="std_twoHT_ROC_pooled_predictions"}
ggplot(twoHT_std_ROC_points_pooled,
       aes(x=FAR, y=HR, color=type, shape=pOld)
       ) +
  geom_line(aes(x=FAR, y=HR, color=type, linetype=strength),
            data = mutate(twoHT_std_ROC_curve_pooled, type="pred"),
            size=1.75,
            inherit.aes = FALSE
            ) +
  geom_line(aes(linetype=strength, group=strength),
            data = filter(twoHT_std_ROC_points_pooled, type=="obs"),
            size=1.75
            ) +
  geom_point(size=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)
                     ) +
  scale_y_continuous("Hit Rate", limits = c(0,1)
                     ) +
  scale_colour_brewer("Model",
                      palette = "Set1",
                      limits = c("obs", "pred"),
                      labels = c("obs" = "Observed",
                                 "pred" = "Two HT")
                      ) +
  scale_linetype_discrete("Strength",
                          limits = c("W", "S"),
                          labels = c("W" = "Weak", "S" = "Strong")
                          ) +
  coord_fixed() +
  ggtitle("Two-HT Model ROC (Pooled Data)") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.size = unit(2, "lines"),
        legend.position = c(.6, .2),
        legend.box = "horizontal")
```


```{r pooled_param_table, dependson=c("std_twoHT_pooled_params", "std_twoHT_pooled_GOF")}
kable(twoHT_std_params_pooled,
      type="HTML",
      digits=3,
      col.names = formatted_names_map[names(twoHT_std_params_pooled)],
      escape=FALSE,
      row.names = FALSE
      ) %>%
  kableExtra::kable_styling(full_width = FALSE)

kable(twoHT_std_GOF_pooled,
      type="HTML",
      digits=3,
      col.names = formatted_names_map[names(twoHT_std_GOF_pooled)],
      escape=FALSE,
      row.names = FALSE
      ) %>%
  kableExtra::kable_styling(full_width = FALSE)
```


## Pooled vs. Averaged Parameter Comparison
```{r pooled_vs_avg_params, dependson=c("std_twoHT_pooled_params", "std_twoHT_GOF")}
x <- gather(twoHT_std_avg_params, "param", "value")
y <- gather(twoHT_std_params_pooled, "param", "value")

ggplot(bind_rows(avg=x, pooled=y, .id="model"),
       aes(x=param, y=value, color=model)
       ) +
  geom_point(size=3) +
  scale_color_discrete(limits=c("pooled","avg"),
                       labels=c("Pooled Data",
                                "Averaged Parameters")
                       ) +
  ggtitle("Pooled vs. Averaged Parameters")

rm(x, y)
```

