---
title: "Discrete Race, Two High Threshold Architecture"
author: "William Hopper"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", cache = TRUE)
library(gamlss.dist)
library(rprojroot)
library(kableExtra)
library(optimx)
library(foreach)
library(dplyr)
library(tidyr)
library(ggplot2)
root_dir <- rprojroot::is_rstudio_project$find_file()
```

```{css css}
.main-container{
  max-width: 1200px;
}
```

```{r discrete_race_exgaussians}
## mu, sigma & nu should be vectors of length 2
## First element should be parameter for detect distribution
## Second element should be parameter for guess distribution

## Weight is also vector of length
## First element is probability of detection being available
## Second element is probability of guessing correctly
## These are independent probabilities, need not sum to 1
dcRT <- function(x, mu, sigma, nu, weights) {
  
  pDetect <- weights[1]
  pGuess_correct <- weights[2]
  
  p_detect_process_unfinished <- gamlss.dist::pexGAUS(x, mu[1], sigma[1], nu[1], lower.tail = FALSE)
  p_guess_process_unfinished <- gamlss.dist::pexGAUS(x, mu[2], sigma[2], nu[2], lower.tail = FALSE)
  
  detect_RT_density <- gamlss.dist::dexGAUS(x, mu[1], sigma[1], nu[1])
  guess_RT_density <- gamlss.dist::dexGAUS(x, mu[2], sigma[2], nu[2])
  
  
  correct_RT_density <- 
    # Detect RT's, weighted by probability you can detect and haven't given up & guessed yet
    pDetect * p_guess_process_unfinished * detect_RT_density + 
    # Guess RT's, weighted by probability you could detect but give up "early" and guess correctly
    pDetect * p_detect_process_unfinished * pGuess_correct * guess_RT_density + 
    # uess RT's, weighted by probability you can not detect but guess correctly
    (1-pDetect) * pGuess_correct * guess_RT_density
  
  return(correct_RT_density)
}

## mu, sigma & nu should be vectors of length 2
## Nu is mean of exponential process (also denoted as tao sometimes)
## First element should be parameter for detect distribution
## Second element should be parameter for guess distribution

## Weight is also vector of length
## First element is probability of detection being available
## Second element is probability of guessing *incorrectly*
## These are independent probabilities, need not sum to 1

deRT <- function(x, mu, sigma, nu, weights) {
  ## mu, sigma & nu should be vectors of length 2
  pDetect <- weights[1]
  pGuess_incorrect <- 1-weights[2]
  
  p_detect_process_unfinished <- gamlss.dist::pexGAUS(x, mu[1], sigma[1], nu[1], lower.tail = FALSE)
  guess_RT_density <- gamlss.dist::dexGAUS(x, mu[2], sigma[2], nu[2])
  
  incorrect_RT_density <- # sum of:
    # Guess RT's, weighted by probability you could detect but give up "early" and guess incorrectly 
    pDetect * p_detect_process_unfinished * pGuess_incorrect * guess_RT_density +
    # Guess RT's, weighted by probability detection is not availble and you guess incorrectly
    (1-pDetect) * pGuess_incorrect * guess_RT_density
  
  return(incorrect_RT_density)
  }
```

```{r discrete_race_objective_functions}

DR_predictions <- function(parameters, data) {
  
  if ( !("mu.dn" %in% names(parameters)) ) {
    parameters["mu.dn"] <- parameters["mu.do"]
  }
  
  data$predicted_p <- numeric(nrow(data))

  for (strength in unique(data$strength)) {

    condition_index <- data$strength==strength
    
    if (strength == "L") {
      mu_detect <- parameters["mu.dn"]
      detect_correctly <- parameters["dNew.L"]
      guess_correctly <- 1 - parameters['gOld']
    } else {
      mu_detect <- parameters["mu.do"]
      detect_correctly <- parameters[paste0('dOld.', strength)]
      guess_correctly <- parameters['gOld']
    }
    
    for (acc in unique(data$speeded_correct)) {

      if (acc) {
        density_fn = dcRT
      } else {
        density_fn = deRT
      }

      index_vector <- condition_index & data$speeded_correct == acc 
      cutpoints <- c(0, data$value[index_vector])
      cutpoints[length(cutpoints)] <- Inf

      p <- numeric(length(cutpoints)-1)
      for (bin_number in 1:length(p)) {

        x <- integrate(density_fn, cutpoints[bin_number], cutpoints[bin_number+1],
                       mu = c(mu_detect, parameters["mu.g"]),
                       sigma = parameters[c("sigma","sigma")],
                       nu = parameters[c("nu","nu")],
                       weights = c(detect_correctly, guess_correctly)
                       )
        p[bin_number] <- x$value
      }

      data$predicted_p[index_vector] <- p
    }
  }

  return(data)
}

DR_quantiles <- function(parameters, data) {

  if ( !("mu.dn" %in% names(parameters)) ) {
    parameters["mu.dn"] <- parameters["mu.do"]
  }
  
  data$predicted_qValue <- numeric(nrow(data))

  for (strength in unique(data$strength)) {

    condition_index <- data$strength==strength
    
    if (strength == "L") {
      mu_detect <- parameters["mu.dn"]
      detect_correctly <- parameters["dNew.L"]
      guess_correctly <- 1 - parameters['gOld']
    } else {
      mu_detect <- parameters["mu.do"]
      detect_correctly <- parameters[paste0('dOld.', strength)]
      guess_correctly <- parameters['gOld']
    }

    n_samples <- 1000
    n_detect_trials <- rbinom(1, size = n_samples, p = detect_correctly)
    detect_RTs <- c(gamlss.dist::rexGAUS(n_detect_trials,
                                         mu = mu_detect,
                                         sigma = parameters["sigma"],
                                         nu = parameters["nu"]),
                    rep(Inf, n_samples - n_detect_trials)
                    )

    guess_RTs <- gamlss.dist::rexGAUS(n_samples,
                                      mu = parameters["mu.g"],
                                      sigma = parameters["sigma"],
                                      nu = parameters["nu"]
                                      )

    RTs <- pmin(detect_RTs, guess_RTs)
    detect_wins <- detect_RTs == RTs
    accuracy <- logical(n_samples)
    accuracy[detect_wins] <- TRUE
    accuracy[!detect_wins] <- as.logical(rbinom(sum(!detect_wins), 1, guess_correctly))

    data$predicted_qValue[data$speeded_correct] <-
      quantile(RTs[accuracy], c(.1, .3, .5, .7, .9, 1))
    
    data$predicted_qValue[!data$speeded_correct] <-
      quantile(RTs[!accuracy], c(.1, .3, .5, .7, .9, 1))
  }

  return(data)
}


DR_obj <- function(parameters, data, fixed=NULL, p_names=NULL) {
  
  if (!is.null(p_names)) {
    names(parameters) <- p_names
    p_names <- names(parameters)
  }

  parameters <- c(parameters, fixed)
  
  if ( !("mu.dn" %in% names(parameters)) ) {
    parameters["mu.dn"] <- parameters["mu.do"]
  }
  
  data$predicted_p <- numeric(nrow(data))
  log_likelihood <- 0

  for (strength in unique(data$strength)) {

    condition_index <- data$strength==strength
    
    if (strength == "L") {
      mu_detect <- parameters["mu.dn"]
      detect_correctly <- parameters["dNew.L"]
      guess_correctly <- 1 - parameters['gOld']
    } else {
      mu_detect <- parameters["mu.do"]
      detect_correctly <- parameters[paste0('dOld.', strength)]
      guess_correctly <- parameters['gOld']
    }

    for (acc in unique(data$speeded_correct)) {

      if (acc) {
        density_fn = dcRT
      } else {
        density_fn = deRT
      }

      index_vector <- condition_index & data$speeded_correct == acc 
      cutpoints <- c(0, data$value[index_vector])
      cutpoints[length(cutpoints)] <- Inf

      p <- numeric(length(cutpoints)-1)
      for (bin_number in 1:length(p)) {

        x <- integrate(density_fn, cutpoints[bin_number], cutpoints[bin_number+1],
                       mu = c(mu_detect, parameters["mu.g"]),
                       sigma = parameters[c("sigma","sigma")],
                       nu = parameters[c("nu","nu")],
                       weights = c(detect_correctly, guess_correctly)
                       )
        p[bin_number] <- x$value
      }

      data$predicted_p[index_vector] <- p
    }

    condition_index <- data$strength==strength
    bin_counts <- data$bin_counts[condition_index]
    log_likelihood <- log_likelihood + dmultinom(x = bin_counts, size = sum(bin_counts),
                                                 prob = data$predicted_p[condition_index],
                                                 log = TRUE)
  }

  return(-log_likelihood)
}
```

```{r load_data}
load(file.path(root_dir, "data", "SvDPRec.Rdata"))
test <- select(test, -list)
```


```{r observed_RT_choice_data}
speeded_RT_choice_quantiles <- filter(test, !is.na(type)) %>%
  filter(speeded_RT > 200) %>%
  mutate(speeded_RT = speeded_RT/1000) %>%
  group_by(subject, strength, speeded_correct) %>%
  summarise(quintiles = list(
              data.frame(quantile = c("10%", "30%", "50%", "70%", "90%", "100%"),
                         value = quantile(speeded_RT, c(.1, .3, .5, .7, .9, 1)),
                         bin_counts = floor(n() * c(.1, .2, .2, .2, .2, .1))
                         )
              )) %>%
  ungroup() %>%
  unnest()

split_data_list <- split(speeded_RT_choice_quantiles,
                         speeded_RT_choice_quantiles$subject
                         )
```

```{r start_cluster, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions", "observed_RT_choice_data")}
cl <- parallel::makeCluster(parallel::detectCores(),
                            outfile = "",
                            methods = FALSE)

doParallel::registerDoParallel(cl)
```

```{r yoked_fit, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions", "observed_RT_choice_data")}

twoHT_DR_yoked_fits <- foreach(sub = split_data_list,
                               .packages = c("gamlss.dist","optimx")
                               ) %dopar%
  {
    starting_theta <- c("dNew.L" = .5, "dOld.W" = .5, "dOld.S"=.75, "gOld"=.5,
                        "mu.do" = .5, "mu.g" = .75, "sigma" = .25, "nu" = .25
                        )
    fit <- optimx(starting_theta,
                  fn = DR_obj,
                  method = c("nmkb", "nlminb"),
                  itnmax = 500,
                  lower = c(.01, .01, .01, .01, .01, .01, .01, .01),
                  upper = c(1,   1,   1,   1,   2,   2,   .5,  .5),
                  control = list(kkt=FALSE, follow.on=TRUE),
                  data = sub,
                  p_names = names(starting_theta))

    fit <- fit[2, ] # Take nlminb result
    fit$subject <- sub$subject[1]
    fit
  }

```

```{r unyoked_fit, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions", "observed_RT_choice_data")}

twoHT_DR_unyoked_fits <- foreach(sub = split_data_list,
                                 .packages = c("gamlss.dist","optimx")
                                 ) %dopar%
  {
    starting_theta <- c("dNew.L" = .5, "dOld.W" = .5, "dOld.S"=.75, "gOld"=.5,
                        "mu.do" = .5, "mu.g" = .75, "mu.dn"=.7, "sigma" = .25, "nu" = .25
                        )
    fit <- optimx(starting_theta,
                  fn = DR_obj,
                  method = c("nmkb", "nlminb"),
                  itnmax = 500,
                  lower = c(.01, .01, .01, .01, .01, 0.01, .01, .01, .01),
                  upper = c(1,   1,   1,   1,   2,   2,    2,   .5,  .5),
                  control = list(kkt=FALSE, follow.on=TRUE),
                  data = sub,
                  p_names = names(starting_theta))

    fit <- fit[2, ] # Take nlminb result
    fit$subject <- sub$subject[1]
    fit
  }

```

```{r fixed_detect_yoked, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions", "observed_RT_choice_data")}

twoHT_params <- read.csv(file.path(root_dir, "vignette", "2HT_detect_params.csv")) %>%
  select(subject, dNew.L = DN, dOld.W = DO_W, dOld.S = DO_S) %>%
  mutate(subject = as.character(subject)) %>%
  split(., .$subject)

twoHT_DR_yoked_Dfixed_fits <- foreach(sub = Map(function(x,y) { list("data"=x, "theta"=y) },
                                                split_data_list, twoHT_params
                                                ),
                                      .packages = c("gamlss.dist","optimx")
                                      ) %dopar%
  {
    starting_theta <- c("gOld"=.5, "mu.do" = .5, "mu.g" = .75, "sigma" = .25, "nu" = .25)
    
    fit <- optimx(par = starting_theta,
                  fn = DR_obj,
                  method = c("nmkb", "nlminb"),
                  itnmax = 500,
                  lower = c(.01, .01, .01, .01, .01),
                  upper = c(1,   2,   2,   .5,  .5),
                  control = list(kkt=FALSE, follow.on=TRUE),
                  data = sub$data,
                  fixed = unlist(sub$theta[2:4]),
                  p_names = names(starting_theta)
                  )

    fit <- fit[2, ]
    A <- attributes(fit)
    fit <- cbind(fit, sub$theta)
    A$names <- c(A$names, names(sub$theta))
    attributes(fit) <- A
    fit
  }

```


```{r stop_cluser, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions", "observed_RT_choice_data")}
parallel::stopCluster(cl)
```


```{r parameters, dependson=c("fixed_detect_yoked", "unyoked_fit", "yoked_fit")}

twoHT_DR_fits <- bind_rows("unyoked" = bind_rows(twoHT_DR_unyoked_fits),
                           "yoked"= bind_rows(twoHT_DR_yoked_fits),
                           "yoked_fixed" = bind_rows(twoHT_DR_yoked_Dfixed_fits),
                           .id = "model"
                           )

fitted_param_list <- lapply(c("unyoked"=twoHT_DR_unyoked_fits,
                              "yoked"=twoHT_DR_yoked_fits,
                              "yoked_fixed" = twoHT_DR_yoked_Dfixed_fits
                              ),
                            FUN = function(x) {
                              columns <- union(c("dNew.L","dOld.W","dOld.S"), colnames(coef(x)))
                              unlist(x[columns])
                              }
                            )

param_names <- lapply(c(twoHT_DR_unyoked_fits[1],
                        twoHT_DR_yoked_fits[1],
                        twoHT_DR_yoked_Dfixed_fits[1]
                        ),
                      function(x) { colnames(coef(x))}
                      ) %>%
  Reduce(union, x = .)

twoHT_DR_params_subject <- select(.data = twoHT_DR_fits, model, subject, !!!param_names)

twoHT_DR_params_avg <- group_by(.data = twoHT_DR_params_subject, model) %>%
  summarise_at(.vars = param_names, .funs = "mean")
```


```{r predicted_probabilities, dependson="parameters"}

predicted_probabilities <- mapply(DR_predictions,
                                  fitted_param_list,
                                  split_data_list,
                                  SIMPLIFY = FALSE
                                  ) %>%
  bind_rows(.id="model") %>%
  mutate(model = sub("[[:digit:]]+", "", model)) %>%
  select(-bin_counts) %>%
  rename(p = predicted_p)


obs_p <- group_by(.data = speeded_RT_choice_quantiles,
           subject, strength, speeded_correct) %>%
  mutate(p = bin_counts/sum(bin_counts)) %>%
  group_by(subject, strength) %>%
  mutate(p = p*c(rep(sum(bin_counts[!speeded_correct])/sum(bin_counts), 6),
                 rep(sum(bin_counts[speeded_correct])/sum(bin_counts), 6))
         ) %>%
  ungroup()


probabilities <- bind_rows(predicted_probabilities,
                           select(mutate(obs_p, model = "obs"), -bin_counts)
                           ) %>% 
  rename(type=model)


accuracy <- group_by(probabilities,
                     type, subject, strength, speeded_correct
                     ) %>%
  summarise(p = sum(p)) %>%
  ungroup()
```

```{r predicted_quantiles, dependson=c("parameters", "predicted_probabilities")}
predicted_quantiles <- mapply(DR_quantiles,
                              fitted_param_list,
                              split_data_list,
                              SIMPLIFY = FALSE
                              ) %>% 
  bind_rows(.id="model") %>%
  mutate(model = sub("[[:digit:]]+", "", model)) %>%
  select(-bin_counts, -value) %>%
  rename(RT = predicted_qValue)

obs_q <- select(speeded_RT_choice_quantiles, -bin_counts) %>%
  mutate(model = "obs") %>%
  rename(RT = value)

quantiles <- bind_rows(predicted_quantiles,
                       obs_q) %>%
  rename(type = model) %>%
  filter(quantile != "100%")

conditional_quantiles <- left_join(quantiles, accuracy,
                                   by = c("type","subject","strength", "speeded_correct")
                                   ) %>%
  mutate(p = p*(as.numeric(sub("%", "", quantile)) / 100))

conditional_quantiles_avg <- group_by(.data = conditional_quantiles,
                                      type, strength, speeded_correct, quantile) %>%
    summarise_at(c("RT","p"), mean) %>%
    ungroup()
```

```{r factor_ordering}
conditional_quantiles_avg <- mutate(conditional_quantiles_avg,
                                    strength = factor(strength, levels = c("L","W","S"))
                                    )
quantiles <- mutate(quantiles, strength = factor(strength, levels = c("L","W","S")))
```


```{r GOF}
null_LL <- group_by(obs_p, subject, strength) %>%
  summarise(LL = dmultinom(bin_counts, sum(bin_counts), p, log=TRUE)) %>%
  group_by(subject) %>%
  summarise(null_LL = sum(LL))

twoHT_DR_GOF_subject <- select(.data = twoHT_DR_fits,
                               subject, model, value, fevals, gevals, niter, convcode) %>%
  mutate(LL = -value) %>%
  left_join(x = .,  y = null_LL,
            by = "subject") %>%
  mutate(G2 = -2*(LL - null_LL)) %>%
  select(subject, model, LL, null_LL, G2, fevals, gevals, niter, convcode)

twoHT_DR_GOF_sum <- group_by(twoHT_DR_GOF_subject, model) %>%
  summarise_at(.vars=c("LL", "null_LL", "G2"), "sum")
```

```{r save_outputs, eval=isTRUE(getOption('knitr.in.progress'))}
files_dir <- paste0(tools::file_path_sans_ext(knitr::current_input()),
                    "_files"
                    )
if (!dir.exists(files_dir)) {
  dir.create(files_dir)
}

write.csv(twoHT_DR_params_subject,
          file = file.path(files_dir, "parameters.csv"),
          row.names = FALSE
          )
write.csv(twoHT_DR_GOF_subject,
          file = file.path(files_dir, "GOF.csv"),
          row.names = FALSE
          )
```


```{r qp_plot, fig.width=10, fig.height=7}

ggplot(conditional_quantiles_avg,
       aes(x=RT, y=p, color=speeded_correct, linetype=type, shape=type)) +
  geom_point(size=2, stroke=1.5) +
  geom_line(size=1) +
  facet_grid(~strength,
             labeller = as_labeller(c("L" = "Lure", "W" = "Weak", "S" = "Strong"))
             ) +
  scale_color_manual("Accuracy",
                     values = RColorBrewer::brewer.pal(3, 'Set1')[1:2],
                     breaks=c("FALSE","TRUE"),
                     labels=c("Incorrect", "Correct")) +
  scale_linetype_manual(NULL,
                        values = c(6,5,2,1),
                        limits=  c("unyoked", "yoked", "yoked_fixed", "obs"),
                        labels = c("unyoked" = "Three Mu's",
                                   "yoked" = "Two Mu's",
                                   "yoked_fixed" = "Two Mu's\nDetect Fixed",
                                   "obs" = "Observed"
                                   )
                          ) +
  scale_shape_manual(NULL,
                     values = c(17, 15, 4, 16),
                     limits=  c("unyoked", "yoked", "yoked_fixed", "obs"),
                     labels = c("unyoked" = "Three Mu's",
                                "yoked" = "Two Mu's",
                                "yoked_fixed" = "Two Mu's\nDetect Fixed",
                                "obs" = "Observed"
                                )
                        ) +
  scale_x_continuous("Response Time (s.)") +
  ggtitle("2HT Discrete Race",
          subtitle="Conditional Quantiles (Average)") +
  theme_bw(base_size=16) +
  theme(plot.title = element_text(hjust=.5),
        plot.subtitle = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.size = unit(1.5, 'lines')
        )
```


```{r param_summary_tables}
formatted_names_map <- c(subject="Subject", model="model", dNew.L="DN<sub>L</sub>", dOld.W="DO<sub>W</sub>", 
                         dOld.S="DO<sub>S</sub>", gOld = "GO", mu.do="μ<sub>D</sub>", mu.g="μ<sub>G</sub>",
                         mu.dn="μ<sub>DN</sub>", sigma="\U03C3", nu="v", G2="G<sup>2</sup>", LL="LL",
                         null_LL="Null LL", df="df", p="p(X<sup>2</sup>)",fevals="fevals",
                         gevals="gevals", niter="niter", convcode="convcode"
                         )

left_join(twoHT_DR_params_subject,
          select(twoHT_DR_GOF_subject, subject, model, G2),
          by=c("subject", "model")
          ) %>%
  kable(digits=3,
        col.names = formatted_names_map[names(.)],
        escape=FALSE) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  kableExtra::column_spec(1:2, bold=TRUE) %>%
  kableExtra::collapse_rows(1)
```


```{r download_links, results="asis"}
cat("<ul><li>",
    paste0('<a href="', file.path(files_dir, "parameters.csv"),
           '">Download Raw Parameters</a>'
           ),
    "</li><li>",
    paste0('<a href="',
           file.path(files_dir, "GOF.csv"),
           '">Download GOF Statistics</a>'
       ),
    "</li></ul>",
    sep=""
    )
```


```{r subject_plots, fig.width=11, fig.align="center", results="asis"}

for (s in unique(speeded_RT_choice_quantiles$subject)) {
  
  cat(sprintf("<h3>Subject %s</h3>", s))
  
  subject_params <- filter(twoHT_DR_params_subject, subject == s) %>%
    select(-subject) %>%
    mutate(dNew.L = cell_spec(round(dNew.L, 3), background=c("#ffffff","#ffffff", "#ff4c4c")),
           dOld.W = cell_spec(round(dOld.W, 3), background=c("#ffffff","#ffffff", "#ff4c4c")),
           dOld.S = cell_spec(round(dOld.S, 3), background=c("#ffffff","#ffffff", "#ff4c4c"))
           )
  
  kable(subject_params,
        digits = 3,
        col.names = formatted_names_map[names(subject_params)],
        escape = FALSE) %>%
    kableExtra::kable_styling(full_width = FALSE) %>%
    print()
  
  subject_GOF <- filter(twoHT_DR_GOF_subject, subject==s) %>%
    select(-subject)
  
  kable(subject_GOF,
        digits = 3,
        col.names = formatted_names_map[names(subject_GOF)],
        escape = FALSE) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  print()
  
  acc_plot <-
    ggplot(filter(accuracy, speeded_correct, subject == s),
           aes(x=strength, y=p, shape=type, color=strength)) +
    geom_point(size=2, stroke=2,
               position = position_dodge(.25)
               ) +
    scale_shape_manual(NULL,
                       values = c(17, 15, 4, 16),
                       limits=  c("unyoked", "yoked", "yoked_fixed", "obs"),
                       labels = c("unyoked" = "Three Mu's",
                                  "yoked" = "Two Mu's",
                                  "yoked_fixed" = "Two Mu's\nDetect Fixed",
                                  "obs" = "Observed"
                                  )
                       ) +
    scale_color_discrete(labels = c("L" = "Lure",
                                    "W" = "Weak\nTarget",
                                    "S" = "Strong\nTarget"),
                         limits = c("L","W","S")
                         ) +
    scale_y_continuous("Percent Correct",
                       limits = c(0, 1),
                       ) +
    scale_x_discrete("", labels = c("","",""),
                     limits = c("L","W","S"),
                     expand = c(0, .2)
                     ) +
    theme(legend.key.height = unit(9, 'mm'),
          axis.ticks.x = element_blank(),
          )
  
  quantile_plot <- 
    ggplot(filter(quantiles, subject == s),
           aes(x=quantile, y=RT, shape=type, color=strength)
           ) +
    geom_point(size=1.5,
               position = position_dodge(.25)
               ) +
    geom_line(aes(group=type),
              position = position_dodge(.25)
              ) +
    facet_grid(speeded_correct ~ strength,
               labeller = labeller(speeded_correct = as_labeller(
                                    c("TRUE" = "Correct",
                                      "FALSE" = "Error")
                                    ),
                                    strength = as_labeller(
                                      c("L" = "Lure",
                                        "S" = "Strong Target",
                                        "W" = "Weak Target")
                                    )
                                   )
               ) +
    scale_shape_manual(NULL,
                       values = c(17, 15, 4, 16),
                       limits=  c("unyoked", "yoked", "yoked_fixed", "obs"),
                       labels = c("unyoked" = "Three Mu's",
                                  "yoked" = "Two Mu's",
                                  "yoked_fixed" = "Two Mu's\nDetect Fixed",
                                  "obs" = "Observed"
                                  )
                       ) +
    scale_color_discrete(labels = c("L" = "Lure",
                                    "W" = "Weak\nTarget",
                                    "S" = "Strong\nTarget"),
                         limits = c("L","W","S")
                         ) +
    scale_y_continuous("RT Quantile Value (s.)") +
    guides(color=FALSE, shape=FALSE)
  
  gridExtra::grid.arrange(acc_plot, quantile_plot, nrow=1,
                          widths=c(.27, .73)
                          )
}
```

