---
title: "Discrete Race Model, Two Low-Threshold Architecture"
author: "William Hopper"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
library(gamlss.dist)
library(rprojroot)
library(kableExtra)
library(optimx)
library(foreach)
library(tidyr)
library(ggplot2)
library(dplyr)
root_dir <- rprojroot::is_rstudio_project$find_file()
```

```{css css}
.main-container{
  max-width: 1200px;
}
```

```{r discrete_race_exgaussians, cache=TRUE}
## mu, sigma & nu should be vectors of length 2
## First element should be parameter for detect distribution
## Second element should be parameter for guess distribution

## Weight is also vector of length
## First element is probability of detection being available
## Second element is probability of guessing correctly
## These are independent probabilities, need not sum to 1
dcRT <- function(x, mu, sigma, nu, weights) {
  
  pDetect_Old <- weights[1]
  pFail <- weights[2]
  pDetect_New <- weights[3]
  pGuess_Correct <- weights[4:6]
  
  p_DO_process_unfinished <- gamlss.dist::pexGAUS(x, mu[1], sigma[1], nu[1], lower.tail = FALSE)
  p_guess_process_unfinished <- gamlss.dist::pexGAUS(x, mu[2], sigma[2], nu[2], lower.tail = FALSE)
  p_DN_process_unfinished <- gamlss.dist::pexGAUS(x, mu[3], sigma[3], nu[3], lower.tail = FALSE)
  
  DO_RT_density <- gamlss.dist::dexGAUS(x, mu[1], sigma[1], nu[1])
  guess_RT_density <- gamlss.dist::dexGAUS(x, mu[2], sigma[2], nu[2])
  DN_RT_density <- gamlss.dist::dexGAUS(x, mu[3], sigma[3], nu[3])
  
  # Detect Old Pathway
  DO <- pDetect_Old * p_guess_process_unfinished * DO_RT_density * pGuess_Correct[3]
  # Detect New Pathway
  DN <- pDetect_New * p_guess_process_unfinished * DN_RT_density * pGuess_Correct[1]
  # Fail to Detect pathway, detection unavailable
  FD <- pFail * guess_RT_density * pGuess_Correct[2]
  # Fail to Detect pathway, guessing beats detect old
  FD_beats_DO <- pDetect_Old * p_DO_process_unfinished * guess_RT_density * pGuess_Correct[2]
  # Fail to Detect pathway, guessing beats detect new
  FD_beats_DN <- pDetect_New * p_DN_process_unfinished * guess_RT_density * pGuess_Correct[2]
  
  correct_RT_density <- DO + DN + FD + FD_beats_DO + FD_beats_DN
  return(correct_RT_density)
}

## mu, sigma & nu should be vectors of length 2
## Nu is mean of exponential process (also denoted as tao sometimes)
## First element should be parameter for detect distribution
## Second element should be parameter for guess distribution

## Weight is also vector of length
## First element is probability of detection being available
## Second element is probability of guessing *incorrectly*
## These are independent probabilities, need not sum to 1

deRT <- function(x, mu, sigma, nu, weights) {
  weights[4:6] <- 1 - weights[4:6]
  incorrect_RT_density <- dcRT(x, mu, sigma, nu, weights)
  return(incorrect_RT_density)
}
```

```{r discrete_race_objective_functions, cache=TRUE}

softmax <- function(x) {
  return(exp(x)/sum(exp(x)))
}

ilogit <- function(x, max=1) {
  return(max/(1+exp(-x)))
}

guess_parameter_scaling <- function(b, reverse=FALSE) {

  # Compute response probabilities from each detect state based on bias parameter
  if (b > 2 || b < -1) {
    stop("Bias parameter must lie within [-1, 2]")
  }
  
  RO_DN <- abs(pmin(b, 0))
  RO_FD <- pmax(pmin(1-b, 1), 0)
  RO_DO <-  2 - pmax(b, 1)
  theta <- c("RO_DN"=RO_DN, "RO_FD"=RO_FD, "RO_DO"=RO_DO)
  
  if (reverse) {
    theta <- 1-theta
  }
  return(theta)
}


parameter_scaling <- function(theta) {

  # Compute response probabilities from each detect state based on bias parameter
  theta["b"] <- -1 + ilogit(x = theta["b"], max=3)
  bias_params <- guess_parameter_scaling(theta["b"])
  
  # Add new vector elements for the parameters that are computed based on existing ones.
  theta <- c(theta, bias_params, "DN_L"=NA_real_, "DN_W"=NA_real_, "DN_S"=NA_real_)

  # Convert detect paramters from log-odds scale to probability scale
  theta[c("DO_L", "FD_L", "DN_L")] <- softmax(c(theta[c("DO_L", "FD_L")], 0))
  theta[c("DO_W", "FD_W", "DN_W")] <- softmax(c(theta[c("DO_W", "FD_W")], 0))
  theta[c("DO_S", "FD_S", "DN_S")] <- softmax(c(theta[c("DO_S", "FD_S")], 0))

  return(theta)
}


pDR <- function(rt, correct, DO, FD, b, mu.do, mu.g, mu.dn, sigma, nu, reverse=FALSE) {

  weights <- c("DO"=DO, "FD"=FD, "DN"=(1-DO-FD),
               guess_parameter_scaling(b, reverse)
               )

  n_correct <- length(correct)
  n_rt <-  length(rt)
  
  if (n_correct != n_rt) {
    if (n_correct == 1) {
      correct <- rep(correct, n_rt)
    } else {
      stop("Length of 'correct' argument vector must be 1, or match length of 'rt' argument vector.")
    }
  }
  
  p <- numeric(length=n_rt)
  for (i in 1:length(p)) {
    
    if (correct[i]) {
      density_fn = dcRT
    } else {
      density_fn = deRT
    }

    x <- integrate(density_fn, 0, rt[i],
                   mu = c(mu.do, mu.g, mu.dn),
                   sigma = c(sigma, sigma, sigma),
                   nu = c(nu, nu, nu),
                   weights = weights
                   )
    p[i] <- x$value
  }

  return(p)
}


qDR <- function(p, correct, DO, FD, b, mu.do, mu.g, mu.dn, sigma, nu, reverse=FALSE) {

  DN <- 1-DO-FD
  weights <- guess_parameter_scaling(b, reverse)
  names(weights) <- c("GC_DN", "GC_FD", "GC_DO")
  
  n_samples <- 10000

  ## DO available Races
  N_DO_trials <- round(DO*n_samples)
  if (N_DO_trials > 0) {
    
    DO_RTs <- rexGAUS(N_DO_trials, mu = mu.do, sigma = sigma, nu = nu)
    guess_RTs <- rexGAUS(N_DO_trials, mu = mu.g, sigma = sigma, nu = nu)
    DO_wins <- DO_RTs <= guess_RTs
    N_DO_wins <- sum(DO_wins)
    
    if (N_DO_wins > 0) {
      
      DO_race_RTs <- ifelse(DO_wins, DO_RTs, guess_RTs)
      DO_race_correct <- numeric(N_DO_trials)
      DO_race_correct[DO_wins] <- rbinom(N_DO_wins, 1, weights["GC_DO"])
      DO_race_correct[!DO_wins] <- rbinom(N_DO_trials - N_DO_wins, 1, weights["GC_FD"])
    
    } else {
      DO_race_RTs <- guess_RTs
      DO_race_correct <- rbinom(N_DO_trials, 1, weights["GC_FD"])
    }
  } else {
    DO_race_RTs <- NULL
    DO_race_correct <- NULL
  }
  
  ## DN available Races
  N_DN_trials <- round(DN*n_samples)
  if (N_DN_trials > 0) {
    
    DN_RTs <- rexGAUS(N_DN_trials, mu = mu.dn, sigma = sigma, nu = nu)
    guess_RTs <- rexGAUS(N_DN_trials, mu = mu.g, sigma = sigma, nu = nu)
    DN_wins <- DN_RTs <= guess_RTs
    N_DN_wins <- sum(DN_wins)
    
    if (N_DN_wins > 0) {
      
      DN_race_RTs <- ifelse(DN_wins, DN_RTs, guess_RTs)
      DN_race_correct <- numeric(N_DN_trials)
      DN_race_correct[DN_wins] <- rbinom(N_DN_wins, 1, weights["GC_DN"])
      DN_race_correct[!DN_wins] <- rbinom(N_DN_trials - N_DN_wins, 1, weights["GC_FD"])
    
    } else {
      DN_race_RTs <- guess_RTs
      DN_race_correct <- rbinom(N_DN_trials, 1, weights["GC_FD"])
    }
  } else {
    DN_race_RTs <- NULL
    DN_race_correct <- NULL
  }

  ## No detection available, non-race RTs
  N_norace_trials <- n_samples - N_DN_trials - N_DO_trials
  if (N_norace_trials > 0){
    norace_RTs <- rexGAUS(N_norace_trials, mu = mu.g, sigma = sigma, nu = nu)
    norace_correct <- rbinom(N_norace_trials, 1, weights["GC_FD"])
  } else {
    norace_RTs <- NULL
    norace_correct <- NULL
  }
  

  RTs <- c(DO_race_RTs, DN_race_RTs, norace_RTs)
  accuracy <- as.logical(c(DO_race_correct, DN_race_correct, norace_correct))

  if (correct) {
    q <- quantile(RTs[accuracy], p)
  } else {
    q <- quantile(RTs[!accuracy], p)
  }
  
  return(q)
}


DR_obj <- function(theta, data, yoke_detect_means=TRUE, fixed=NULL, p_names = NULL) {

  if (!is.null(p_names)) {
    names(theta) <- p_names
  }

  theta <- c(theta, fixed)
  
  if (yoke_detect_means) {
    theta["mu.dn"] <- theta["mu.do"]
  }
  
  theta <- parameter_scaling(theta)
  
  data$predicted_p <- numeric(nrow(data))
  
  log_likelihood <- 0
  
  for (strength in unique(data$strength)) {

    condition_index <- data$strength==strength
    DO <- theta[paste0("DO_", strength)]
    FD <- theta[paste0("FD_", strength)]
    
    for (acc in unique(data$speeded_correct)) {

      index_vector <- condition_index & data$speeded_correct == acc
      rt_cutpoints <- data$value[index_vector]
      rt_cutpoints[length(rt_cutpoints)] <- Inf

      p <- pDR(rt = rt_cutpoints, correct = acc,
               DO = DO, FD = FD,
               b = theta["b"],
               mu.do = theta["mu.do"], mu.g=theta["mu.g"], mu.dn=theta["mu.dn"],
               sigma = theta["sigma"], nu=theta["nu"],
               reverse = strength == "L"
               )

      data$predicted_p[index_vector] <- diff(c(0, p))
    }

    invalid_p <- data$predicted_p[condition_index] <= 0
    if (any(invalid_p))  {
      data$predicted_p[condition_index][invalid_p] <- 1e-10
    }
    
    bin_counts <- data$bin_counts[condition_index]
    log_likelihood <- log_likelihood + dmultinom(x = bin_counts, size = sum(bin_counts),
                                                 prob = data$predicted_p[condition_index],
                                                 log = TRUE)
  }

  return(-log_likelihood)
}
```

```{r load_data}
load(file.path(root_dir, "data", "SvDPRec.Rdata"))
test <- select(test, -list)
```

```{r observed_RT_choice_data}
speeded_RT_choice_quantiles <- filter(test, !is.na(type)) %>%
  filter(speeded_RT > 200) %>%
  mutate(speeded_RT = speeded_RT/1000) %>%
  group_by(subject, strength, speeded_correct) %>%
  summarise(quintiles = list(
              data.frame(quantile = c("10%", "30%", "50%", "70%", "90%", "100%"),
                         value = quantile(speeded_RT, c(.1, .3, .5, .7, .9, 1)),
                         bin_counts = floor(n() * c(.1, .2, .2, .2, .2, .1))
                         )
              )) %>%
  ungroup() %>%
  unnest()
```

```{r fit, cache=TRUE, dependson=c("discrete_race_exgaussians", "discrete_race_objective_functions")}

twoLT_DR_fits_optimx <- foreach(sub = split(speeded_RT_choice_quantiles,
                                            speeded_RT_choice_quantiles$subject)
                                ) %do% {

    starting_theta <- c("DO_L"=0.01, "FD_L"=0.01, "DO_W"=0.01, "FD_W"=0.01,
                        "DO_S" = 0.01, "FD_S" = 0.01, "b" = .5,
                        "mu.do" = .5, "mu.g" = .75, "sigma" = .25, "nu" = .25
                        )
    fit <- optimx(starting_theta,
                  fn = DR_obj,
                  method = c("nmkb","nlminb"),
                  itnmax = 500,
                  lower = c(-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 0.01, 0.01, .01, .01),
                  upper = c( Inf,  Inf,  Inf,  Inf,  Inf,  Inf,  Inf, 2,    2,    .5,  .5),
                  control = list(kkt=FALSE, follow.on=TRUE),
                  data = sub,
                  p_names = names(starting_theta))

    fit <- fit[2,]
    fit$subject <- sub$subject[1]
    fit
  }

twoLT_DR_threeMu_fits_optimx <- foreach(sub = split(speeded_RT_choice_quantiles,
                                            speeded_RT_choice_quantiles$subject)
                                ) %do% {
    starting_theta <- c("DO_L"=0.01, "FD_L"=0.01, "DO_W"=0.01, "FD_W"=0.01,
                        "DO_S" = 0.01, "FD_S" = 0.01, "b" = .5,
                        "mu.do" = .5, "mu.g" = .75, "mu.dn" = .5, "sigma" = .25, "nu" = .25
                        )
    fit <- optimx(starting_theta,
                  fn = DR_obj,
                  method = c("nmkb","nlminb"),
                  itnmax = 500,
                  lower = c(-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 0.01, 0.01, 0.01, .01, .01),
                  upper = c( Inf,  Inf,  Inf,  Inf,  Inf,  Inf,  Inf, 2,    2,    2,    .5,  .5),
                  control = list(kkt=FALSE),
                  data = sub,
                  yoke_detect_means=FALSE,
                  p_names = names(starting_theta)
                  )
    fit <- fit[2,]
    fit$subject <- sub$subject[1]
    fit
  }

twoLT_DR_fits <- bind_rows(yoked=bind_rows(twoLT_DR_fits_optimx),
                           unyoked=bind_rows(twoLT_DR_threeMu_fits_optimx),
                           .id="model"
                           )
```

```{r parameters}
parameter_names <- colnames(coef(twoLT_DR_threeMu_fits_optimx[[1]]))

twoLT_DR_params_subject <- dplyr::select(twoLT_DR_fits, subject, model, !!!parameter_names)

twoLT_DR_params_scaled_subject <- rowwise(twoLT_DR_params_subject) %>%
  do({
    data.frame(subject = .$subject,
               model= .$model,
               as.list(parameter_scaling(unlist(.[parameter_names]))),
               stringsAsFactors = FALSE
               )
    }) %>%
  ungroup() %>%
  dplyr::select(subject, model, !!!parameter_names)

twoLT_DR_params_avg <- group_by(twoLT_DR_params_subject, model) %>%
  summarise_at(.vars = parameter_names, "mean")
twoLT_DR_params_scaled_avg <- group_by(twoLT_DR_params_scaled_subject, model) %>%
  summarise_at(.vars = parameter_names, "mean")
```

```{r GOF}
null_LL <- speeded_RT_choice_quantiles %>%
  group_by(subject, strength, speeded_correct) %>%
  mutate(p = bin_counts/sum(bin_counts)) %>%
  group_by(subject, strength) %>%
  mutate(marginal_p = p*c(rep(sum(bin_counts[!speeded_correct])/sum(bin_counts), 6),
                          rep(sum(bin_counts[speeded_correct])/sum(bin_counts), 6))
         ) %>%
  summarise(LL = dmultinom(bin_counts, sum(bin_counts), marginal_p, log=TRUE)) %>%
  group_by(subject) %>%
  summarise(null_LL = sum(LL))



twoLT_DR_GOF_subject <- dplyr::select(.data=twoLT_DR_fits,
                                      subject, model, value, fevals, gevals, niter, convcode) %>%
  mutate(LL = -value) %>%
  left_join(x = .,  y = null_LL,
            by = "subject") %>%
  mutate(G2 = -2*(LL - null_LL),
         ## FIND A BETTER WAY TO COMPUTE SUBJECTWISE DF FOR EACH MODEL
         df = 33 - c(rep(length(parameter_names)+1, 14), rep(length(parameter_names), 14)),
         p = pchisq(G2, df = df, lower.tail = FALSE)
         ) %>%
  dplyr::select(subject, model, LL, null_LL, G2, df, p, fevals, gevals, niter, convcode)

twoLT_DR_GOF_sum <- group_by(twoLT_DR_GOF_subject, model) %>%
  summarise_at(.vars=c("LL", "null_LL", "G2", "df"), "sum")
```

```{r condition_wise_parameters}
detect_params <-
  select(twoLT_DR_params_scaled_subject, subject, model, contains("_")) %>%
  gather(key="param", value="value", -subject, -model) %>%
  separate(param, c("param", "strength")) %>%
  spread(param, value)

strength_wise_params <- left_join(detect_params,
                                  select(twoLT_DR_params_scaled_subject, -contains("_")),
                                  by = c("subject","model")
                                  )

variables <- setdiff(names(strength_wise_params), c("subject", "model", "strength"))

condition_wise_params <- bind_rows(mutate(strength_wise_params, speeded_correct = FALSE),
                                   mutate(strength_wise_params, speeded_correct = TRUE)
                                   ) %>% 
  select(subject, model, strength, speeded_correct, !!!variables)
```


```{r predicted_accuracy, cache=TRUE, dependson="fit"}

predicted_probabilities <- mutate(condition_wise_params,
                                  mu.dn = coalesce(mu.dn, mu.do)) %>%
  left_join(x=.,
            y=select(speeded_RT_choice_quantiles, -bin_counts),
            by = c("subject", "strength", "speeded_correct")
            ) %>% 
  rowwise() %>%
  mutate(predicted_p = pDR(rt=value, correct=speeded_correct,
                           DO, FD, b, mu.do, mu.g, mu.dn, sigma, nu,
                           reverse = strength == "L")
         ) %>%
  ungroup() %>%
  select(-variables) %>%
  group_by(subject, model, strength, speeded_correct) %>%
  mutate(predicted_p = diff(c(0, predicted_p))) %>%
  ungroup()

predicted_acc <- filter(predicted_probabilities, speeded_correct) %>%
  group_by(subject, model, strength) %>%
  summarise(predicted_acc = sum(predicted_p)) %>%
  ungroup()

observed_acc <- group_by(speeded_RT_choice_quantiles,
                         subject, strength) %>%
  summarise(acc = sum(bin_counts[speeded_correct])/sum(bin_counts)) %>%
  ungroup()

accuracy <- bind_rows(twoLT = rename(predicted_acc, acc = predicted_acc),
                      obs = observed_acc,
                      .id = "type"
                      ) %>%
  unite("type", type, model) %>%
  mutate(strength = factor(strength, levels = c("L","W","S")))
```

```{r predicted_quantiles, cache=TRUE, dependson="fit"}

predicted_quantiles <-
  mutate(condition_wise_params,
         mu.dn = coalesce(mu.dn, mu.do)) %>%
  rowwise() %>%
  mutate(predicted_q = list(as.data.frame(as.list(
    qDR(p=c(.1, .3, .5, .7, .9, 1),
        correct = speeded_correct,
        DO, FD, b, mu.do, mu.g, mu.dn, sigma, nu,
        reverse = strength == "L"
        )
      ),
    check.names=FALSE)
    )) %>%
  ungroup() %>%
  select(subject, model, strength, speeded_correct, predicted_q) %>%
  unnest() %>%
  gather(key="quantile", value="value", contains("%"), factor_key = TRUE) %>%
  arrange(subject, model, strength, speeded_correct)

quantiles <- bind_rows(twoLT = predicted_quantiles,
                       obs = select(speeded_RT_choice_quantiles, -bin_counts),
                       .id="type")  %>%
  unite("type", type, model) %>%
  mutate(strength = factor(strength, levels = c("L","W","S")))

conditional_quantiles_subject <-
  mutate(accuracy, inc=1-acc) %>%
  gather(key="speeded_correct", value="p", acc, inc) %>%
  mutate(speeded_correct = ifelse(speeded_correct=="acc", TRUE, FALSE)) %>%
  right_join(quantiles,
             by = c("subject", "strength", "speeded_correct", "type")
             ) %>%
  filter(quantile != "100%") %>%
  mutate(p = p * as.numeric(sub("%", "", quantile, fixed = TRUE))/100) %>%
  rename(RT = value)

conditional_quantiles_avg <-
  group_by(.data = conditional_quantiles_subject,
           type, strength, speeded_correct, quantile
           ) %>%
  summarise_at(c("RT","p"), mean) %>%
  ungroup()
```

```{r save_outputs, eval=isTRUE(getOption('knitr.in.progress'))}
files_dir <- paste0(tools::file_path_sans_ext(knitr::current_input()),
                    "_files"
                    )
if (!dir.exists(files_dir)) {
  dir.create(files_dir)
}

write.csv(twoLT_DR_params_subject,
          file = file.path(files_dir, "parameters.csv"),
          row.names = FALSE
          )
write.csv(twoLT_DR_params_scaled_subject,
          file = file.path(files_dir, "scaled_parameters.csv"),
          row.names = FALSE
          )
write.csv(twoLT_DR_GOF_subject,
          file = file.path(files_dir, "GOF.csv"),
          row.names = FALSE
          )
```

```{r qp_plot, fig.width=10, fig.height=7}
ggplot(conditional_quantiles_avg,
       aes(x=RT, y=p, color=speeded_correct, linetype=type, shape=type)) +
  geom_point(size=3) +
  geom_line(size=1) +
  facet_grid(~strength,
             labeller = as_labeller(c("L" = "Lure", "W" = "Weak", "S" = "Strong"))
             ) +
  scale_color_manual("Accuracy",
                     values = RColorBrewer::brewer.pal(3, 'Set1')[1:2],
                     breaks=c("FALSE","TRUE"),
                     labels=c("Incorrect", "Correct")) +
  scale_linetype_manual(NULL,
                        values = c(5, 2, 1),
                        limits = c("twoLT_unyoked", "twoLT_yoked", "obs_NA"),
                        labels = c("twoLT_yoked" = "Two Mu's",
                                   "twoLT_unyoked" = "Three Mu's",
                                   "obs_NA" = "Observed")
                        ) +
  scale_shape_manual(NULL,
                     values = c(17, 15, 16),
                     limits = c("twoLT_unyoked", "twoLT_yoked", "obs_NA"),
                     labels = c("twoLT_yoked" = "Two Mu's",
                                "twoLT_unyoked" = "Three Mu's",
                                "obs_NA" = "Observed")
                     ) +
  guides(color = guide_legend(order = 1)) +
  ggtitle("2LT Discrete Race",
          subtitle="Conditional Quantiles (Average)") +
  scale_x_continuous("Response Time (s.)") +
  theme_bw(base_size=16) +
  theme(plot.title = element_text(hjust=.5),
        plot.subtitle = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(2,"line")
        )
```

```{r param_summary_tables}
formatted_names_map <- c(subject="Subject", model="model", DO_L="DO<sub>L</sub>", FD_L="FD<sub>L</sub>",
                         DO_W="DO<sub>W</sub>", FD_W="FD<sub>W</sub>", DO_S="DO<sub>S</sub>",
                         FD_S="FD<sub>S</sub>", b="b", mu.do="μ<sub>D</sub>", mu.g="μ<sub>G</sub>",
                         mu.dn="μ<sub>DN</sub>", sigma="\U03C3", nu="v", G2="G<sup>2</sup>", LL="LL",
                         null_LL="Null LL", df="df", p="p(X<sup>2</sup>)",fevals="fevals",
                         gevals="gevals", niter="niter", convcode="convcode"
                         )
#"p(X<sup>2</sup><sub>28</sub>)")

left_join(twoLT_DR_params_scaled_subject,
          select(twoLT_DR_GOF_subject, subject, model, G2),
          by=c("subject", "model")
          ) %>%
  select(model, subject, !!!parameter_names, G2) %>%
  kable(digits=3,
        col.names = formatted_names_map[names(.)],
        escape=FALSE) %>%
  kableExtra::kable_styling(full_width = FALSE) %>%
  kableExtra::column_spec(1:2, bold=TRUE) %>%
  kableExtra::collapse_rows(1)
```

```{r download_links, results="asis"}
cat("<ul><li>",
    paste0('<a  href="', file.path(files_dir, "scaled_parameters.csv"),
           '">Download Scaled Parameters</a>'
           ),
    "</li><li>",
    paste0('<a href="', file.path(files_dir, "parameters.csv"),
           '">Download Raw Parameters</a>'
           ),
    "</li><li>",
    paste0('<a href="',
           file.path(files_dir, "GOF.csv"),
           '">Download GOF Statistics</a>'
       ),
    "</li></ul>",
    sep=""
    )
```


## Individual Subjects
```{r subject_plots, cache=TRUE, fig.width=11, fig.align="center", results="asis", dependson="fit"}

for (s in unique(speeded_RT_choice_quantiles$subject)) {
  
  cat(sprintf("<h3>Subject %s</h3>", s))
  
  subject_params <- filter(twoLT_DR_params_scaled_subject, subject == s)[,-1]
  subject_GOF <- filter(twoLT_DR_GOF_subject, subject == s)[,-1]

  kable(subject_params,
        digits=3,
        row.names=FALSE,
        col.names = formatted_names_map[names(subject_params)],
        escape = FALSE) %>%
    kableExtra::kable_styling(full_width = FALSE, position = "float_left") %>%
    kableExtra::column_spec(1, bold=TRUE) %>%
    print()
  
    kable(subject_GOF,
          digits = 3,
          row.names = FALSE,
          col.names = formatted_names_map[names(subject_GOF)],
          escape = FALSE) %>% 
    kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
    kableExtra::column_spec(1, bold=TRUE) %>%
    print()

  acc_plot <-
    ggplot(filter(accuracy, subject == s),
          aes(x=strength, y=acc, shape=type, color=strength)) +
    geom_point(size=2, stroke=2,
               position = position_dodge(width=.35)
               ) +
    scale_shape_manual("",
                       values = c(16, 4, 3),
                       limits = c("obs_NA", "twoLT_yoked", "twoLT_unyoked"),
                       labels = c("Observed", "Two Mu's", "Three Mu's"),
                       ) +
    scale_color_discrete("Strength",
                         labels = c("L" = "Lure",
                                    "W" = "Weak\nTarget",
                                    "S" = "Strong\nTarget")
                         ) +
    scale_y_continuous("Percent Correct", limits = c(0, 1)) +
    scale_x_discrete("", labels = c("","",""),
                     limits = c("L","W","S"),
                     expand = c(0, .25)
                 ) +
    theme(legend.key.height = unit(9, 'mm'),
          axis.ticks.x = element_blank(),
          )
  
  quantile_plot <- 
    ggplot(filter(quantiles, subject == s, quantile != "100%"),
           aes(x=quantile, y=value, shape=type, color=strength)) +
    geom_point(size=1.5) +
    geom_line(aes(group=type)) +
    facet_grid(speeded_correct ~ strength,
               labeller = labeller(speeded_correct = as_labeller(
                                    c("TRUE" = "Correct",
                                      "FALSE" = "Error")
                                    ),
                                    strength = as_labeller(
                                      c("L" = "Lure",
                                        "S" = "Strong Target",
                                        "W" = "Weak Target")
                                    )
                                   )
               ) +
    scale_shape_manual(values = c(16, 4, 3),
                       limits = c("obs_NA","twoLT_yoked", "twoLT_unyoked")
                       ) +
    scale_y_continuous("RT Quantile Value (s.)") +
    guides(color=FALSE, shape=FALSE)
  
  gridExtra::grid.arrange(acc_plot, quantile_plot, nrow=1,
                          widths=c(.27, .73))
}
```

