---
title: "Participants Summary"
author: "William Hopper"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

<style>
  img {max-width: 150%;}
  #dataset-description {overflow: auto;}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
library(rprojroot)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(kableExtra)

root_dir <- rprojroot::is_rstudio_project$find_file()
source(file.path(root_dir, "R","load_data.R"))
```

```{r load_data}
test <- load_data("Test")
```

```{r score}
test <- mutate(test,
               speeded_correct = (type == "T" & speeded_judgment == "o") |
                                 (type == "L" & speeded_judgment == "n"),
               delayed_correct = (type == "T" & delayed_judgment == "o") |
                                 (type == "L" & delayed_judgment == "n")) %>%
  select(subject, session, trial:strength, word, 
         speeded_judgment, speeded_RT, speeded_correct,
         delayed_judgment, delayed_RT, delayed_correct)
```

## Dataset Description
```{r n_per_sub_session}
n_per_sub_session <- count(test, subject, session)

spread(n_per_sub_session, session, n, fill = 0) %>%
  rename(Subject = subject) %>%
  knitr::kable(caption = "Trials per subject and session") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "float_left") %>%
  kableExtra::add_header_above(c(" " = 1,
                                 "Session" = length(unique(n_per_sub_session$session)))
                               )
```

```{r base_rates}
count(test, pOld, type) %>%
  mutate(type = factor(type, levels=c("L","T",NA), exclude=NULL,
                       labels = c("Lure","Target", "XXXXXX"))
         ) %>%
  kable(col.names = c("p(Old)", "Probe Type", "Count"),
        caption = "Base rate of probe types") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "float_left") %>%
  kableExtra::column_spec(1, bold = T, color = "black") %>%
  kableExtra::collapse_rows(1)
```

```{r trimming}
# Discard catch trials from main dataset
catch_trials <- is.na(test$type)
catch <- test[catch_trials, ]
test <- test[!catch_trials, ]
# Remove very fast responses
test <- filter(test, speeded_RT > 200)
rm(catch_trials)
```

```{r transitions}
transitions <- test %>%
  count(pOld, speeded_judgment, delayed_judgment) %>%
  group_by(pOld) %>%
  mutate(percent = n/sum(n)) %>%
  select(-n) %>%
  mutate_at(c("speeded_judgment", "delayed_judgment"), factor, labels = c("New", "Old")) %>%
  spread(key = delayed_judgment, value = percent)

kable(transitions, format = "html",
      col.names = c("p(Old)", "Speeded", "New", "Old"),
      digits=3,
      caption = "Speeded/Delayed judgment contingency table, grouped by bias hint level.") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
  kableExtra::add_header_above(c(" " = 2, "Delayed" = 2)) %>%
  kableExtra::column_spec(1, bold = T, color = "black") %>%
  kableExtra::collapse_rows(1)
```

## Recognition Accuracy
```{r accuracy_per_sub_session}
percent_correct_per_sub_session <- test %>%
  group_by(subject, session) %>%
  summarise_at(c("speeded_correct", "delayed_correct"), mean) %>%
  gather(key = "judgment", value = "PC", speeded_correct, delayed_correct) %>%
  mutate(judgment = factor(sub("_correct", "", judgment, fixed = TRUE),
                           levels = c("speeded","delayed"),
                           labels = c("Speeded", "Delayed")),
         session = factor(session))

```

```{r accuracy_per_sub_session_display}
PC_sub_session_plot <-
  ggplot(percent_correct_per_sub_session,
         aes(x=session, y=PC, group=subject)) +
  geom_point(size=1.5) +
  geom_line(size=.7) +
  facet_wrap(judgment~.) +
  scale_x_discrete("Session", expand = c(0,.5)) +
  scale_y_continuous("Percent Correct") +
  ggtitle("Recognition Accuracy") +
  theme_bw(base_size = 15) +
  theme(plot.title = element_text(hjust = .5))

subject_number_annotations <- 
  geom_text_repel(aes(label=subject),
                  direction = "y",
                  data = filter(percent_correct_per_sub_session,
                                session == 4),
                  nudge_x = 15, hjust = 0,
                  min.segment.length = 1,
                  box.padding = .15, 
                  arrow = arrow(length = unit(0.02, "npc"),
                                type = "open",
                                ends = "last")
                  )
print(PC_sub_session_plot + subject_number_annotations)  
```

```{r dprime_per_sub_session}
speeded_counts_by_sub_session <- test %>%
  count(subject, session, strength, speeded_correct) %>%
  complete(subject, session, strength, speeded_correct,
           fill = list(n=0)) %>%
  rename(correct = speeded_correct)

delayed_counts_by_sub_session_bias <- test %>%
  count(subject, session, strength, pOld, delayed_correct) %>%
  complete(subject, session, strength, pOld, delayed_correct,
           fill = list(n=0)) %>%
  rename(correct = delayed_correct)

dprime_by_sub_session <- bind_rows("speeded" = speeded_counts_by_sub_session,
                                   "delayed" = group_by(delayed_counts_by_sub_session_bias,
                                                        subject, session, strength, correct) %>%
                                       summarise(n = sum(n)),
                                   .id = "judgment") %>%
  select(subject, session, judgment, strength, correct, n) %>%
  unite(col = "resp_type", strength, correct) %>%
  spread(resp_type, n) %>%
  rename(FA = L_FALSE, CR = L_TRUE,
         M_S = S_FALSE, H_S = S_TRUE,
         M_W = W_FALSE, H_W = W_TRUE) %>%
  mutate(S_dprime = qnorm(H_S/(M_S + H_S)) - qnorm(FA/(FA + CR)),
         S_dprime = replace(S_dprime, S_dprime == Inf, qnorm(1-1/(2*H_S[S_dprime == Inf]))),
         W_dprime = qnorm(H_W/(M_W + H_W)) - qnorm(FA/(FA + CR))) %>%
  gather(key = "strength", value = "dprime", S_dprime, W_dprime) %>%
  mutate(strength = factor(sub("_dprime", "", strength), levels = c("S","W"),
                           labels = c("Strong", "Weak")),
         judgment = factor(judgment, levels = c("speeded","delayed"),
                           labels = c("Speeded", "Delayed")),
         session = factor(session)
         )
```

```{r dprime_per_sub_session_display, fig.height=8}
dprime_sub_sesssion_plot <- ggplot(dprime_by_sub_session,
                                   aes(x=session, y=dprime, group=subject)) +
  geom_point(size=1.5) +
  geom_line(size=.7) +
  geom_text_repel(aes(label=subject),
                  direction = "y",
                  data = filter(dprime_by_sub_session, session == 4),
                  nudge_x = 15, hjust = 0,
                  min.segment.length = 1, box.padding = .15, 
                  arrow = arrow(length = unit(0.02, "npc"),
                                type = "open",
                                ends = "last")
                  ) +
  facet_grid(strength ~ judgment) +
  scale_x_discrete("Session", expand = c(0,.5)) +
  scale_y_continuous("d'") +
  ggtitle("Recognition Discriminability") +
  theme_bw(base_size = 15) +
  theme(plot.title = element_text(hjust = .5))

print(dprime_sub_sesssion_plot)
```

```{r percent_correct}
speeded_pc_by_subject_strength <- test %>%
  group_by(subject, strength) %>%
  summarise(speeded_pc = mean(speeded_correct)) %>%
  ungroup()

speeded_pc_by_strength <- speeded_pc_by_subject_strength %>%
  group_by(strength) %>%
  summarise(speeded_pc = mean(speeded_pc)) %>%
  ungroup()

delayed_pc_by_subject_strength_bias <- test %>%
  mutate(pOld = factor(pOld)) %>%
  group_by(subject, strength, pOld) %>%
  summarise(delayed_pc = mean(delayed_correct)) %>%
  ungroup()

delayed_pc_by_strength_bias <- delayed_pc_by_subject_strength_bias %>%
  group_by(strength, pOld) %>%
  summarise(delayed_pc = mean(delayed_pc)) %>%
  ungroup()
```

```{r percent_corect_display}
ggplot(speeded_pc_by_subject_strength,
       aes(x=strength, y=speeded_pc)) +
  geom_point(color='darkgray', size=2,
             position=position_jitter(width = .1)) +
  geom_point(data=speeded_pc_by_strength, size=4) +
  scale_x_discrete("Item Type",
                   limits=c("Lure"="L", "Weak"="W", "Strong"="S"),
                   labels=c("L"="Lure", "W"="Weak", "S"="Strong")
                   ) +
  scale_y_continuous("Percent Correct",
                     labels = scales::percent_format(accuracy = 1)) +
  ggtitle("Speeded Recognition Accuracy") +
  theme_bw(base_size = 16)

ggplot(delayed_pc_by_subject_strength_bias,
       aes(x=strength, y=delayed_pc, shape=pOld)) +
  geom_point(color='darkgray',
             size=2,
             position=position_jitterdodge(dodge.width = .6, jitter.width = .1)) +
  geom_point(data=delayed_pc_by_strength_bias,
             size=4,
             position=position_dodge(width = .6)) +
  scale_x_discrete("Item Type",
                   limits=c("Lure"="L", "Weak"="W", "Strong"="S"),
                   labels=c("L"="Lure", "W"="Weak", "S"="Strong")
                   ) +
  scale_y_continuous("Percent Correct",
                     labels=scales::percent_format(accuracy = 1),
                     breaks=c(.2, .4, .6, .8, 1)) +
  scale_shape_discrete("p(Studied)",
                       labels = c("0.25"="25%", "0.5"="50%", "0.75"="75%")) +
  ggtitle("Delayed Recognition Accuracy") +
  theme_bw(base_size = 16) +
  theme(legend.position = c(0.88, .15),
        plot.title = element_text(hjust = .5))
```


## Empirical R.O.C. Function
```{r ROC_by_subject}
ROC_by_sub <- group_by(delayed_counts_by_sub_session_bias,
                       subject, strength, pOld, correct) %>%
  summarise(n = sum(n)) %>%
  unite(col = "resp_type", strength, correct) %>%
  spread(resp_type, n) %>%
  rename(FA = L_FALSE, CR = L_TRUE,
         M_S = S_FALSE, H_S = S_TRUE,
         M_W = W_FALSE, H_W = W_TRUE) %>%
  mutate(FAR = FA/(FA + CR),
         W_HR = H_W/(M_W + H_W),
         S_HR = H_S/(M_S + H_S)) %>%
  select(subject, pOld, FAR, W_HR, S_HR) %>%
  gather("strength", "HR", W_HR, S_HR) %>%
  mutate(strength = factor(strength, levels=c("W_HR","S_HR")))
```

```{r ROC_by_subject_display, fig.height=18, fig.width=10}
ggplot(ROC_by_sub, aes(x=FAR, y=HR, color = factor(pOld), group=subject)) +
  geom_line(size=.8, color="black") +
  geom_point(size=2) +
  facet_wrap(~ subject + strength ,
             labeller = labeller(
               strength = as_labeller(c("W_HR" = "'Weak' Target",
                                        "S_HR" = "'Strong' Target")
                                      ),
               subject = label_both,
               .multi_line = FALSE),
             ncol=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_color_manual("p(Old)",
                     values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4))) +
  coord_fixed() +
  ggtitle("ROC for delayed judgments") +
  theme_bw(base_size = 13) +
  theme(legend.position='top')
```

## Response Time
```{r response_times}
RT_by_sub_session_type <- test %>%
  select(subject, session, strength, speeded_judgment, speeded_RT) %>%
  group_by(subject, session, strength, speeded_judgment) %>%
  summarise(speeded_RT= list(as.data.frame(t(
    quantile(speeded_RT, c(.1, .5, .9))
    )))) %>%
  ungroup() %>%
  unnest(speeded_RT)

RT_by_sub_type_acc <- test %>%
  select(subject, strength, speeded_correct, speeded_RT) %>%
  group_by(subject, strength, speeded_correct) %>%
  summarise(speeded_RT= list(as.data.frame(t(
    quantile(speeded_RT, c(.1, .5, .9))
    )))) %>%
  ungroup() %>%
  unnest(speeded_RT)
```

```{r response_times_display1, fig.height=18, fig.width=10}
ggplot(RT_by_sub_session_type,
       aes(x=session, y=`50%`, color=strength,
           group=interaction(subject,strength)
           )
       ) +
  geom_point(size=2) +
  geom_line() +
  facet_wrap(~ subject + speeded_judgment,
             labeller = labeller(subject=label_both,
                                 speeded_judgment=as_labeller(c("n" = "'New'", 
                                                                "o" = "'Old'")),
                                 .multi_line = FALSE),
             ncol=4, scales = "free_y"
             ) +
  scale_y_continuous("Median RT") +
  scale_color_discrete(labels = c("L"="Lure", "W"="Weak","S"="Strong"),
                       breaks = c("L","W","S"),
                       position="top") +
  ggtitle("Response time by subject and session") +
  theme_bw(base_size = 14) +
  theme(legend.position='top')
```

```{r response_times_display2, fig.height=10, fig.width=7}
ggplot(RT_by_sub_type_acc,
       aes(x=subject, y=`50%`, ymin=`10%`, ymax=`90%`)
       ) +
  geom_point(size=2) +
  geom_errorbar() +
  facet_grid(strength ~ speeded_correct,
             labeller = labeller(speeded_correct = as_labeller(
                                    c("FALSE" = "Incorrect",
                                      "TRUE" = "Correct")
                                    ),
                                 strength = as_labeller(
                                    c("L"="Lure", "W"="Weak","S"="Strong")
                                 )
             )) +
  scale_y_continuous("Median RT") +
  ggtitle("Response time by subject") +
  theme_bw(base_size = 14)
```

```{r median_RT}
RT_median_by_sub <- test %>%
  select(subject, strength, speeded_correct, speeded_RT) %>%
  group_by(subject, strength, speeded_correct) %>%
  summarise(median_RT = median(speeded_RT)) %>%
  ungroup()

RT_avg_median <- RT_median_by_sub %>%
  group_by(strength, speeded_correct) %>%
  summarise(avg_median = mean(median_RT)) %>%
  ungroup()
```

```{r median_RT_display}
ggplot(RT_median_by_sub,
       aes(x=strength, y=median_RT, shape=speeded_correct)
       ) + 
  geom_point(alpha=.5, size=1.5,
             position=position_jitterdodge(dodge.width = .6, jitter.width = .1)) +
  geom_point(aes(y=avg_median), data=RT_avg_median, size=4,
             position=position_dodge(width = .6)) +
  scale_x_discrete("Item Type",
                   limits=c("Lure"="L", "Weak"="W", "Strong"="S"),
                   labels=c("L"="Lure", "W"="Weak", "S"="Strong")
                   ) +
  scale_y_continuous("Median Response Time (ms.)") +
  scale_shape_discrete("Recognition Accuracy",
                       labels=c("TRUE"="Correct", "FALSE"="Incorrect")) +
  guides(shape=guide_legend(nrow=1)) +
  theme_bw(base_size = 16) +
  theme(legend.position = c(0.5, .915))
```
