---
title: "UVSD Modeling"
author: "William Hopper"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{css css, include=FALSE}
.main-container {
    max-width: 1100px;
  }
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", cache = TRUE)
library(rprojroot)
library(kableExtra)
library(optimx)
library(foreach)
library(rstan)
library(tidybayes)
library(ggplot2)
library(tidyr)
library(dplyr)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
root_dir <- rprojroot::is_rstudio_project$find_file()
```

```{r load_data, cache.extra = tools::md5sum(file.path(root_dir, "data","SvDPRec.Rdata"))}
load(file.path(root_dir, "data","SvDPRec.Rdata"))
test <- select(test, -list)
```

```{r cell_counts, dependson=c("load_data")}
delayed_counts_by_sub_bias <- filter(test, !is.na(type)) %>%
  select(-starts_with("speeded")) %>%
  rename(correct = delayed_correct) %>%
  count(subject, strength, pOld, correct) %>%
  complete(subject, strength, pOld, correct,
           fill = list(n=0)) %>%
  unite(col = "resp_type", strength, correct) %>%
  spread(resp_type, n) %>%
  rename(FA = L_FALSE, CR = L_TRUE,
         M_S = S_FALSE, H_S = S_TRUE,
         M_W = W_FALSE, H_W = W_TRUE) %>%
  mutate(L_N = FA + CR,
         S_N = M_S + H_S,
         W_N = M_W + H_W) %>%
  select(subject, pOld, FA, L_N, H_S, S_N, H_W, W_N)

```

```{r empirical_roc_data, dependson="cell_counts"}
obs_ROC_data <- mutate(delayed_counts_by_sub_bias,
                       FAR = FA/L_N,
                       HR_W = H_W/W_N,
                       HR_S = H_S/S_N,
                       pOld = sprintf("%2.0f%%", pOld*100)) %>%
  select(subject, pOld, FAR, HR_W, HR_S) %>%
  gather(key="strength", value="HR", HR_W, HR_S) %>%
  mutate(strength = sub("HR_", "", strength)) %>%
  select(subject, pOld, strength, FAR, HR)

avg_obs_ROC_data <- group_by(obs_ROC_data, pOld, strength) %>%
  summarise_at(.vars = c("FAR", "HR"), .funs = "mean") %>%
  ungroup()
```

```{r null_LL, dependson=c("cell_counts")}
null_LL <- mutate(delayed_counts_by_sub_bias,
                  FA_LL = dbinom(FA, L_N, FA / L_N, log = TRUE),
                  HW_LL = dbinom(H_W, W_N, H_W / W_N, log = TRUE),
                  HS_LL = dbinom(H_S, S_N, H_S / S_N, log = TRUE),
                  LL = FA_LL + HW_LL + HS_LL) %>%
  select(subject, pOld, LL) %>%
  group_by(subject) %>%
  summarise(null_LL = sum(LL))
```

## Subject-wise Maximum Likelihood Estimation
```{r SDT_model_functions}
SDT <- function(d, s, crit) {

  # if (is.unsorted(rev(crit))) {
  #   # warning("Criterion locations will be sorted in descending order")
  #   crit <- sort(crit, decreasing = TRUE)
  # }
  
  if (length(d) != 2L) {
    stop("Only 2 target distributions may be specified")
  }

  if (length(s) == 1L) {
    s <- c(s, s)
  }
  
  FAR <- pnorm(crit, lower.tail = FALSE)
  HR_W <- pnorm(crit, mean = d[1], sd = s[1], lower.tail = FALSE)
  HR_S <- pnorm(crit, mean = d[2], sd = s[2], lower.tail = FALSE)
  
  return(list("HitRate_Strong" = HR_S,
              "HitRate_Weak" = HR_W,
              "FalseAlarmRate" = FAR)
         )
}

SDT_LL <- function(H_S, H_W, FA, ...) {

  SDT_preds <- SDT(...)
  LL <- c(dbinom(H_S$H_S, size = H_S$S_N, prob = SDT_preds$HitRate_Strong, log=TRUE),
          dbinom(H_W$H_W, size = H_W$W_N, prob = SDT_preds$HitRate_Weak, log=TRUE),
          dbinom(FA$FA, size = FA$L_N, prob = SDT_preds$FalseAlarmRate, log=TRUE)
          )
  return(-sum(LL))
}

## A small wrapper around the likelihood function that makes it suitable
## for optimization. It takes the parameter values as a named vector, matching the 
## vector element names with argument names for the SDT_LL function. It also detects
## whether the likelhood function is infinite (which optimx et al. doesn't like), and
## instead returns the largest representable on the current machine.

fit_SDT <- function(theta, ...) {

  negLL <- SDT_LL(d = theta[c("d.W","d.S")],
                  s = theta[startsWith(names(theta), "s")],
                  crit = theta[c("crit1", "crit2", "crit3")],
                  ...)
  if (is.infinite(negLL) || is.nan(negLL)) {
    negLL <- .Machine$double.xmax
  }

  return(negLL)
}
```

```{r MLE_fit, dependson=c("cell_counts", "SDT_model_functions")}
UVSD_fits_optimx <- foreach(sub = split(delayed_counts_by_sub_bias,
                                        delayed_counts_by_sub_bias$subject)
                     ) %do% {

  fit <- optimx(par = c("d.W"=1.5, "d.S"=2.5, "s" = 1.2,
                        crit = c(1.25, 1, .75)),
                fn = fit_SDT,
                method = "nlminb",
                itnmax = 3000,
                lower = c(0, 0, 0.1, 0.1, -3, -3, -3),
                upper = c(4, 4, 2, 2, 3, 3, 3),
                control = list(kkt=FALSE),
                H_S = sub[c("H_S","S_N")],
                H_W = sub[c("H_W", "W_N")],
                FA = sub[c("FA", "L_N")]
              )
  ## Add subject number as first column of fit table
  fit$subject <- sub$subject[1]
  fit <- select(fit, subject, d.W:convcode)
  
  ## Order the criterion columns from largest (most conservative) to lowest (most liberal)
  crit_columns <- startsWith(names(fit), "crit")
  decreasing_crit_values <- sort(unlist(fit[crit_columns]), decreasing = TRUE)
  names(decreasing_crit_values) <- paste0("crit", 1:length(decreasing_crit_values))
  fit[crit_columns] <- as.list(decreasing_crit_values)
  
  ## This is a max lik fit, so "Value" so it should be renamed and have sign flipped (as optimization routine minimized negative LL)
  fit <- rename(fit, LL = value)
  fit <- mutate(fit, LL = -LL)
  
  }

UVSD_MLE_fits <- bind_rows(UVSD_fits_optimx)
```

```{r MLE_parameter_summaries, dependson="MLE_fit"}
UVSD_MLE_params <- select(.data = UVSD_MLE_fits,
                          subject, d.W, d.S, s, c.C = crit1, c.N = crit2, c.L = crit3)
UVSD_MLE_params_avg <- mutate(UVSD_MLE_params,
                              s = s^2) %>%
  summarise_at(.vars = c("d.W", "d.S", "s", "c.C", "c.N", "c.L"),
               .funs = "mean") %>%
  mutate(s = sqrt(s))
```

```{r MLE_GOF, dependson="MLE_fit"}
UVSD_MLE_GOF <- select(UVSD_MLE_fits, subject, LL, fevals, gevals, niter, convcode) %>%
  left_join(null_LL, by="subject") %>%
  mutate(calc_G2 = -2*(LL - null_LL)) %>%
  mutate(df = 3,
         p.value = pchisq(calc_G2, df=df, lower.tail = FALSE)
         ) %>%
  select(subject, LL, null_LL, calc_G2, df, p.value, fevals:convcode)

UVSD_MLE_GOF_sum <- select(.data = UVSD_MLE_GOF,
                            subject, LL, null_LL, calc_G2, df) %>%
  summarise_at(.vars = c("LL", "null_LL", "calc_G2", "df"),
               .funs = "sum"
               ) %>%
  mutate(p.value = pchisq(calc_G2, df=df, lower.tail = FALSE))

rm(UVSD_MLE_fits)
```

```{r MLE_ROC_predictions, dependson="MLE_parameter_summaries"}
FAR_points <- seq(0, 1, .01)

MLE_ROC_preds <- rowwise(UVSD_MLE_params) %>%
  mutate(SDT = list(
    data.frame(FAR = rep(FAR_points, 2),
               HR = pnorm(c((qnorm(FAR_points) + d.W)/s,
                            (qnorm(FAR_points) + d.S)/s
                          )),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels=c("W","S"))
               )
  )) %>%
  select(subject, SDT) %>%
  unnest()

MLE_ROC_preds_avg <-
  summarise(.data = UVSD_MLE_params_avg,
            SDT = list(data.frame(
                FAR = rep(FAR_points, 2),
                HR = pnorm(c((qnorm(FAR_points) + d.W)/s,
                             (qnorm(FAR_points) + d.S)/s
                           )),
                strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                levels=c("W","S")
                                )
                ))
            )%>%
  unnest()
```

```{r MLE_ROC_avg_plot, fig.width=9, dependson="MLE_ROC_predictions"}
ggplot(MLE_ROC_preds_avg,
       aes(x=FAR, y=HR, linetype=strength)) +
  geom_line(size=1.75) +
  geom_point(aes(color=factor(pOld)),
             data = avg_obs_ROC_data,
             size=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_linetype_discrete("Item",
                          labels=c("W" = "'Weak' Target",
                                   "S" = "'Strong' Target")) +
  scale_color_manual("p(Old)", values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(size = 4))) +
  coord_fixed() +
  ggtitle("UVSD Model ROC (Average)") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(10,"mm")
        )
```

```{r MLE_tables, dependson=c("MLE_GOF", "MLE_parameter_summaries")}
parameter_colnames <- c("d'<sub>W</sub>", "d'<sub>S</sub>", "\u03c3",
                        "C<sub>c</sub>", "C<sub>n</sub>", "C<sub>l</sub>")

bind_rows(UVSD_MLE_params,
          mutate(UVSD_MLE_params_avg, subject = "Mean")
          ) %>%
  kable(digits=3, type="HTML", escape = FALSE,
        caption = "MLE parameter estimates",
        col.names = c("Subject", parameter_colnames)
        ) %>%
  kableExtra::kable_styling(full_width = FALSE, position = "float_left") %>%
  column_spec(1, bold = TRUE)

bind_rows(select(.data = UVSD_MLE_GOF,
                 subject, LL, null_LL, calc_G2, df, p.value),
          mutate(.data = UVSD_MLE_GOF_sum,
                 subject = "Sum")
          ) %>%
  kable(type="HTML", digits=3,
        caption = "MLE Goodness of Fit") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "float_left") %>%
  column_spec(1, bold = TRUE)
```

```{r MLE_ROC_sub_plot, fig.width=9, fig.height=9, dependson="MLE_ROC_predictions"}
ggplot(MLE_ROC_preds,
       aes(x=FAR, y=HR, linetype=strength)) +
  geom_line(size=1.75) +
  geom_point(aes(color=factor(pOld)),
             data = obs_ROC_data,
             size=2) +
  facet_wrap(~subject, labeller = label_both) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_linetype_discrete("Item",
                          labels=c("W" = "'Weak' Target",
                                   "S" = "'Strong' Target")) +
  scale_color_manual("p(Old)", values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(size = 4))) +
  ggtitle("UVSD Model ROC") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(10,"mm"),
        legend.position = c(.7, .10),
        legend.box = "horizontal")
```

## Hierarchical Bayesian Estimation
### Will's Stan Model
```{stan stan_model_external, cache=FALSE, eval=FALSE, echo=TRUE, output.var='modelstring', code=readLines(file.path(root_dir, "R","UVSD.stan"))}
```

```{r stan_model, results="hide", cache.extra = tools::md5sum(file.path(root_dir, "R","UVSD.stan"))}
# Create an array suitable for passing into stan, so it can be turned into an array of matrices
# The final produce should be 14 x 3 x 3, with subject along dim 1, bias level (conservative --> liberal) along dim 2,
# and strength (lure, weak, strong) along dim 3.
delayed_counts_by_sub_bias <- arrange(delayed_counts_by_sub_bias, subject, desc(pOld))

yes_matrix = t(as.matrix(delayed_counts_by_sub_bias[c('FA','H_W','H_S')]))
dim(yes_matrix) <- c(3, 3, 14)
dimnames(yes_matrix) <- list("Strength" = c("Lure","Weak","Strong"),
                             "Bias" = c("Lib.","Neutral","Cons."),
                             "Subject" = 101:114)
yes_matrix <- aperm(yes_matrix, c(2,1,3))

trial_matrix = t(as.matrix(delayed_counts_by_sub_bias[c('L_N','W_N','S_N')]))
dim(trial_matrix) <- c(3, 3, 14)
dimnames(trial_matrix) <- list("Strength" = c("Lure","Weak","Strong"),
                               "Bias" = c("Lib.","Neutral","Cons."),
                               "Subject" = 101:114)
trial_matrix <- aperm(trial_matrix, c(2,1,3))

standata <- list(yeses = yes_matrix, trials = trial_matrix,
                 Nsubs = length(unique(delayed_counts_by_sub_bias$subject)))

fit <- stan(file = file.path(root_dir, "R","UVSD.stan"),
            data = standata,
            pars = paste0("eta[", 1:standata$Nsubs, "]"),
            include = FALSE,
            iter = 3000,
            chains = 4,
            seed = 1235,
            init_r = 1,
            control = list(adapt_delta=.99)
            )
```

```{r Stan_parameter_summaries, cache=TRUE, dependson=c("stan_model")}
posterior <- as.data.frame(rstan::extract(fit))

## Subject level parameters
sub_level_params <- select(posterior, contains("_sub")) %>%
  summarise_all(.funs = funs(mean, median)) %>%
  gather("parameter","value") %>%
  separate(parameter, into = c("parameter", "statistic"),
         sep = "(?<=[0-9])_", fill = "right") %>%
  separate(parameter, into = c("parameter","subject","which"),
           sep = "\\.", fill = "right", convert = TRUE) %>%
  mutate(subject = as.character(subject + 100))

subject_dprimes <- filter(sub_level_params, parameter=="mu_sub", statistic=="mean") %>%
  mutate(strength = ifelse(which==1,"Weak","Strong")) %>%
  select(subject, strength, value) %>%
  spread(strength, value) %>%
  select(subject, Weak, Strong)

sub_sigma <- filter(sub_level_params, parameter=="sigma_sub", statistic=="mean") %>%
  select(subject, parameter, value) %>%
  spread(parameter, value) %>%
  rename(sigma = sigma_sub)

sub_crit <- filter(sub_level_params, parameter=="crit_sub", statistic=="mean") %>%
  select(subject, parameter, which, value) %>%
  unite("parameter", parameter, which) %>%
  spread(parameter, value) %>%
  select(subject, crit_sub_3, crit_sub_2, crit_sub_1)

sub_param_means <- inner_join(subject_dprimes, sub_sigma, by = "subject") %>%
  inner_join(sub_crit, by="subject")

sub_param_means_avg <- select(sub_param_means, -subject) %>%
  mutate(sigma = sigma^2) %>%
  colMeans() %>%
  as.data.frame(x = t(.)) %>%
  mutate(sigma = sqrt(sigma))

## Hyper Parameters
hyper <- select(posterior, contains("_pop")) %>%
  summarise_all(.funs = funs(mean)) %>%
  mutate(sigma_pop = exp(log_sigma_pop),
         sigma_pop_SD = exp(log_sigma_pop_SD)) %>%
  select(d.W_mu = mu_pop.1, d.W_sd = mu_pop_SD.1, d.S_mu=mu_pop.2, d.S_sd = mu_pop_SD.2,
         sigma_mu = sigma_pop, sigma_sd = sigma_pop_SD,
         crit_pop.3, crit_pop_SD.3, crit_pop.2, crit_pop_SD.2, crit_pop.1, crit_pop_SD.1)
```

```{r Stan_ROC_predictions, dependson=c("Stan_parameter_summaries")}
Stan_ROC_preds <- rowwise(sub_param_means) %>%
  mutate(SDT = list(
    data.frame(FAR = rep(FAR_points, 2),
               HR = pnorm(c((qnorm(FAR_points) + Weak)/sigma,
                            (qnorm(FAR_points) + Strong)/sigma
                          )),
               strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                 levels=c("W","S"))
               )
  )) %>%
  select(subject, SDT) %>%
  unnest()

Stan_ROC_preds_hyper <-
  summarise(.data = hyper,
            SDT = list(data.frame(
                FAR = rep(FAR_points, 2),
                HR = pnorm(c((qnorm(FAR_points) + d.W_mu)/sigma_mu,
                             (qnorm(FAR_points) + d.S_mu)/sigma_mu
                           )),
                strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                levels=c("W","S")
                                )
                ))
            )%>%
  unnest()

Stan_ROC_preds_avg <-
  summarise(.data = sub_param_means_avg,
            SDT = list(data.frame(
                FAR = rep(FAR_points, 2),
                HR = pnorm(c((qnorm(FAR_points) + Weak)/sigma,
                            (qnorm(FAR_points) + Strong)/sigma
                           )),
                strength = factor(rep(c("W", "S"), each = length(FAR_points)),
                                levels=c("W","S")
                                )
                ))
            )%>%
  unnest()
```

```{r Stan_ROC_population_plot, dependson=c("Stan_ROC_predictions")}
ggplot(MLE_ROC_preds_avg,
       aes(x=FAR, y=HR, linetype=strength)) +
  geom_line(size=1.75) +
  geom_point(aes(color=factor(pOld)),
             data = avg_obs_ROC_data,
             size=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_linetype_discrete("Item",
                          labels=c("W" = "'Weak' Target",
                                   "S" = "'Strong' Target")) +
  scale_color_manual("p(Old)", values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(size = 4))) +
  coord_fixed() +
  ggtitle("UVSD Model ROC",subtitle = "Population Paramters") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(10,"mm")
        )

ggplot(Stan_ROC_preds_avg,
       aes(x=FAR, y=HR, linetype=strength)) +
  geom_line(size=1.75) +
  geom_point(aes(color=factor(pOld)),
             data = avg_obs_ROC_data,
             size=4) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_linetype_discrete("Item",
                          labels=c("W" = "'Weak' Target",
                                   "S" = "'Strong' Target")) +
  scale_color_manual("p(Old)", values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(size = 4))) +
  coord_fixed() +
  ggtitle("UVSD Model ROC",subtitle = "Averaged Subject Parameters") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(10,"mm")
        )
```

```{r stan_posterior_summary_tables, dependson=c("Stan_parameter_summaries")}
kable(sub_param_means, digits=3, escape = FALSE,
      caption = "Subject-level parameter means",
      col.names = c("Subject", parameter_colnames)) %>%
  kable_styling(full_width = FALSE, position = "left")

hyperparam_colnames <- rep(c("\u03BC", "\u03c3"), 6)

kable(hyper, digits=3, escape = FALSE,
      caption = "Hyperparameter means",
      col.names = hyperparam_colnames) %>%
  kable_styling(full_width = FALSE, position = "left") %>%
  add_header_above(setNames(rep(2, 6), parameter_colnames),
                   escape = FALSE)
```


```{r Stan_ROC_sub_plot, fig.width=9, fig.height=9, dependson=c("Stan_ROC_predictions")}
ggplot(Stan_ROC_preds,
       aes(x=FAR, y=HR, linetype=strength)) +
  geom_line(size=1.75) +
  geom_point(aes(color=factor(pOld)),
             data = obs_ROC_data,
             size=2) +
  facet_wrap(~subject, labeller = label_both) +
  scale_x_continuous("False Alarm Rate", limits = c(0,1),
                     labels = c(0,0.25, 0.5, 0.75, 1)) +
  scale_y_continuous("Hit Rate", limits = c(0,1)) +
  scale_linetype_discrete("Item",
                          labels=c("W" = "'Weak' Target",
                                   "S" = "'Strong' Target")) +
  scale_color_manual("p(Old)", values = c("#d82d2d", "#d8d834", "#17b50c")) +
  guides(colour = guide_legend(override.aes = list(size = 4)),
         shape = guide_legend(override.aes = list(size = 4))) +
  ggtitle("UVSD Model ROC") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=.5),
        strip.background = element_blank(),
        legend.key.width = unit(10,"mm"),
        legend.position = c(.7, .10),
        legend.box = "horizontal")
```


### Parameter Correlations
```{r MLE_vs_bayes_point, dependson=c("Stan_parameter_summaries", "MLE_parameter_summaries")}
ggplot(bind_rows(MLE = select(UVSD_MLE_params, subject, Weak = d.W, Strong = d.S, sigma = s,
                              crit_C = c.C, crit_N = c.N, crit_L = c.L),
                 Bayes = rename(sub_param_means, crit_C = crit_sub_3,
                                crit_N = crit_sub_2, crit_L = crit_sub_1),
                 .id = "model") %>%
         gather("param","value", -subject, -model) %>%
         spread(model, value) %>%
         mutate(param = factor(param, levels=c("Weak","Strong","sigma",
                                               "crit_L", "crit_N","crit_C"),
                               labels = c('d[W]','d[S]',"sigma",'C[L]','C[N]','C[C]'))
                ),
       aes(x=MLE, y=Bayes)) +
  geom_point(size=2) +
  geom_abline(slope = 1, intercept = 0) +
  facet_wrap(~param, labeller = label_parsed)
```

### Jeff's JAGS Model
```{r jags_model_source_code, cache=FALSE, comment=""}
cat(readLines(file.path(root_dir, "R", "uv.bug")), sep="\n")
```

```{r jags_model}
## loads mcmc.list object named 'UVSD_jags_posterior'
load(file = file.path(root_dir, "data", "uvPosts.RData"))
```

```{r jags_parameter_summaries, dependson="jags_model"}
jags_posterior_subjects <- spread_draws(UVSD_jags_posterior, mu[subject], se[subject], lsig[subject],
                                        bec[subject], c[subject], bel[subject]) %>%
  mutate(strong = mu + se,
         sigma = exp(lsig),
         crit1 = (mu/2) + c + bec,
         crit2 = (mu/2) + c,
         crit3 = (mu/2) + c + bel) %>%
  select(.chain:subject, Weak=mu, Strong = strong, sigma, crit1, crit2, crit3) %>%
  mean_hdi() %>%
  mutate(subject = as.character(subject + 100))

jags_posterior_hyper <- spread_draws(UVSD_jags_posterior, Mmu, SDmu, Mse, SDse, Mlsig, SDlsig,
                                     Mbec, Mc, Mbel, SDc, SDbe) %>%
  mutate(strong = Mmu + Mse,
         sigma = exp(Mlsig),
         SDsigma = exp(SDlsig),
         crit1 = (Mmu/2) + Mc + Mbec,
         crit2 = (Mmu/2) + Mc,
         crit3 = (Mmu/2) + Mc + Mbel) %>%
  select(.chain:.draw, weak=Mmu, SDweak=SDmu, strong, SDstrong=SDse, sigma, SDsigma,
         crit1, SDbe, crit2, SDc, crit3) %>%
  mean_hdi()
```

```{r jags_posterior_summary_tables, dependson="jags_parameter_summary"}
kable(select(jags_posterior_subjects, -contains(".")),
      digits=3, escape = FALSE,
      caption = "Subject-level parameter means",
      col.names = c("Subject", parameter_colnames)) %>%
  kable_styling(full_width = FALSE, position = "left") 

kable(select(jags_posterior_hyper, -contains(".")),
      digits=3, escape = FALSE,
      caption = "Hyperparameter means",
      col.names = hyperparam_colnames[-length(hyperparam_colnames)]) %>%
  kable_styling(full_width = FALSE, position = "left") %>%
  add_header_above(c(setNames(rep(2, 5), parameter_colnames[1:(length(parameter_colnames)-1)]), 
                     "C<sub>l</sub>"=1),
                   escape = FALSE)
```

```{r JAGS_vs_Stan, dependson=c("jags_parameter_summaries", "Stan_parameter_summaries")}
ggplot(bind_rows(stan = rename(sub_param_means, crit_C = crit_sub_3,
                                crit_N = crit_sub_2, crit_L = crit_sub_1),
                 jags = rename(select(jags_posterior_subjects, -contains(".")),
                               crit_C = crit1, crit_N = crit2, crit_L = crit3),
                 .id = "model") %>%
         gather("param","value", -subject, -model) %>%
         spread(model, value) %>%
         mutate(param = factor(param, levels=c("Weak","Strong","sigma",
                                               "crit_L", "crit_N","crit_C"),
                               labels = c('d[W]','d[S]',"sigma",'C[L]','C[N]','C[C]'))
                ),
       aes(x=jags, y=stan)) +
  geom_point(size=2) +
  geom_abline(slope = 1, intercept = 0) +
  xlab("JAGS") +
  ylab("Stan") +
  facet_wrap(~param, labeller = label_parsed)
```